import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'je-countability',
  title: '数え方で意味が変わる英語：可算・不可算と冠詞',
  summary: '買い物や食事の場面から、名詞の数え方、a・an・the、some・any・much・manyを使い分ける。同じ単語でも「材料」と「一つの品」で扱いが変わる理由を学ぶ。',
  objectives: [
    '名詞がその場面で個体・材料・抽象的な内容のどれを表すか判断する。',
    '可算名詞の単数・複数と不可算名詞に合う冠詞や数量表現を選ぶ。',
    '相手が対象を特定できるかを根拠に、a・anとtheを区別する。',
    'some・any・much・manyの基本用法と、依頼や注文での意味の変化を説明する。',
  ],
  blocks: [
    { type: 'note', variant: 'info', content: 'このレッスンの英語例文・会話・問題はすべて学習用の自作です。標準的な日常英語の基本用法を扱います。語の意味や地域・場面によって数え方が変わるため、知らない語は辞書の意味ごとの［C］（可算）・［U］（不可算）も確認しましょう。' },
    { type: 'heading', level: 3, content: '1　「現実に数えられるか」だけでは決まらない' },
    { type: 'text', content: '**可算名詞**は一つずつ区別するものとして扱い、a book、two booksのように表します。**不可算名詞**は材料や量、ひとまとまりの内容として扱い、water、informationのように使います。米粒は現実には数えられても、食材としてのriceは通常不可算です。「小さいから不可算」「目に見えないから不可算」という判定はできません。' },
    { type: 'table', headers: ['その意味での扱い', '基本の形', '注意点'], rows: [
      ['可算・単数', 'a chair / an apple / my book', '通常の文中では単数を裸で置かず、a・the・myなどを伴う'],
      ['可算・複数', 'chairs / two apples / some books', '複数形を使う。不規則形もある：one child → two children'],
      ['不可算', 'water / some rice / much information', 'その意味では通常a・anや複数形にしない'],
    ] },
    { type: 'text', content: 'たとえばI have homework.（宿題がある）は正しい文です。homeworkは通常不可算なので、「宿題が三つ」をthree homeworksとはしません。課題の数ならthree assignments（課題三つ）などと表します。advice（助言）やfurniture（家具）も、日本語の感覚だけで複数形にしないよう注意しましょう。' },
    { type: 'heading', level: 3, content: '2　a・anは一つ、theは「どれか分かる」' },
    { type: 'text', content: '**a・anは可算名詞の単数**に用い、「ある一つの」「一つの種類の成員」を示します。I need a bag.なら、まだ特定していない袋が一つ必要です。aとanは次の語のつづりでなく、直後の音で選びます。an apple、an hour（hを発音しない）、a useful bag（usefulの始まりは「ユ」に近い子音）となります。' },
    { type: 'text', content: '**theは、聞き手もどの対象か特定できる**ことを示します。単数・複数・不可算のいずれにも使えます。the bag、the bags、the waterが可能です。既に話した物だけでなく、二人の前にドアが一つしかないなら、初めて話題にしてもPlease close the door.（そのドアを閉めてください）と言えます。' },
    { type: 'example', title: '例題1：初登場と二度目で冠詞を変える', body: '話し手も聞き手も特定の本を想定していません。「昨日、本を一冊買いました。その本は星についての本です」を、I bought ___ book yesterday. ___ book is about stars. の空欄を埋めて表しましょう。', answer: '**a / The**。最初は未特定の一冊なのでa book。次は買ったその本だと分かるのでThe bookです。文頭のTheは大文字にします。単に「二度目だから」ではなく、相手が同じ本だと特定できることが根拠です。' },
    { type: 'text', content: '種類全般を表す基本形は、可算名詞なら冠詞なしの複数、不可算名詞なら冠詞なしです。Cats need water.（猫には水が必要です）は猫と水を一般的に述べます。一方、The cats need the water in this bowl.なら、特定の猫たちと、このボウルの水を指します。my bagのような形には、さらにaやtheを重ねません。' },
    { type: 'heading', level: 3, content: '3　不可算名詞は「容器・単位」を数える' },
    { type: 'table', headers: ['言いたい内容', '英語', '複数になる語'], rows: [
      ['水をコップ一杯', 'a glass of water', '一杯なのでglassは単数'],
      ['水をコップ二杯', 'two glasses of water', '容器を表すglass → glasses'],
      ['パンを三切れ', 'three slices of bread', '切れを表すslice → slices'],
      ['助言を二つ', 'two pieces of advice', '個々の内容を区切るpiece → pieces'],
    ] },
    { type: 'example', title: '例題2：人数と量を別に表す', body: '4人に一人1杯ずつ水を出します。コップはすべて200 mL入りで、満杯にします。用意する杯数と水の合計量を求め、杯数を英語で表しましょう。', answer: '**four glasses of water（水をコップ4杯）**。4人 × 一人1杯 = 4杯。1杯200 mLなので、4 × 200 = 800 mLです。複数形になるのはglassesで、waterではありません。実際のglass一杯の容量は一定ではなく、800 mLという値はこの問題の200 mLという条件によります。' },
    { type: 'heading', level: 3, content: '4　some・anyは「いくつか／いくらか」' },
    { type: 'text', content: 'someとanyは、基本用法では**可算名詞の複数にも不可算名詞にも**使えます。some applesは「いくつかのリンゴ」、some milkは「いくらかの牛乳」。肯定文ではsome、否定文や中立的な疑問文ではanyがよく使われます。I have some milk. / I do not have any milk. / Do you have any milk? と比べましょう。' },
    { type: 'note', variant: 'warn', content: '「疑問文なら必ずany」は誤りです。Would you like some tea?（お茶はいかがですか）は提供、Can I have some water?（水をもらえますか）は依頼です。ある程度「ある・受け入れてもらえる」ことを見込む場面でsomeを使います。また、肯定文のYou can choose any book.ではany bookが「どの本でも」の意味になり、単数にも使えます。基本表だけで機械的に決めないことが大切です。' },
    { type: 'example', title: '例題3：牛乳があるか尋ねる／飲み物を勧める', body: '①在庫を知らずにDo you have any milk?と尋ねる。②用意した牛乳を相手にWould you like some milk?と勧める。anyとsomeの違いを場面と結び付けて説明しましょう。', answer: '①は牛乳があるかどうかの中立的な質問なのでanyが自然です。②は飲んでもらうための申し出なのでsomeが自然です。どちらもmilkは不可算で、疑問符の有無だけが選択の根拠ではありません。Do you have some milk?も、あることを期待する文脈などでは可能です。' },
    { type: 'heading', level: 3, content: '5　manyは個数、muchは量' },
    { type: 'table', headers: ['表現', '続く名詞', '自作例文と意味'], rows: [
      ['many / How many', '可算名詞の複数', 'How many eggs do we need?（卵はいくつ必要？）'],
      ['much / How much', '不可算名詞', 'How much milk do we need?（牛乳はどれくらい必要？）'],
      ['a lot of', '可算複数・不可算の両方', 'We have a lot of eggs and a lot of milk.（卵も牛乳もたくさんある）'],
    ] },
    { type: 'text', content: '日常会話の普通の肯定文では、特にmuchよりa lot ofが自然なことが多く、We have a lot of time.（時間がたくさんある）などと言います。much・manyは疑問文・否定文でよく使いますが、肯定文で使えないわけではありません。Many people like this park.も正しい文です。なおHow much is this bag?は「このかばんはいくら？」という値段の質問で、bagを不可算としているのではありません。' },
    { type: 'heading', level: 3, content: '6　同じ語でも、何を指すかで数え方が変わる' },
    { type: 'table', headers: ['語', '不可算の意味の例', '可算の意味の例'], rows: [
      ['chicken', 'We ate chicken.（鶏肉を食べた）', 'They keep three chickens.（ニワトリを3羽飼っている）'],
      ['glass', 'This bottle is made of glass.（この瓶はガラス製だ）', 'There are two glasses on the table.（コップが二つある）'],
      ['coffee', 'I like coffee.（コーヒーが好きだ）', 'Two coffees, please.（注文で：コーヒーを2杯ください）'],
      ['cake', 'I ate some cake.（ケーキをいくらか食べた）', 'She baked two cakes.（ケーキを丸ごと二つ焼いた）'],
    ] },
    { type: 'text', content: 'coffeeは飲み物そのものなら不可算ですが、注文では「一杯分」を一単位としてa coffeeやtwo coffeesと言えます。種類を数える文脈でも可算になることがあります。ただし、どの不可算名詞も自由に複数形にできるわけではありません。adviceを「助言二つ」のつもりでtwo advicesとは通常言わず、two pieces of adviceとします。' },
    { type: 'example', title: '例題4：aが付いたら何を数えている？', body: '食卓でWe had chicken for dinner.、農場でWe saw a chicken.と聞きました。chickenをどう訳し分けますか。', answer: '前者は**夕食に鶏肉を食べた**。食材を量として扱う不可算のchickenです。後者は**ニワトリを1羽見た**。一羽の動物を指す可算のa chickenです。aがあるかだけを暗記するのではなく、食材と動物という意味の違いを確かめます。' },
    { type: 'heading', level: 3, content: '7　場面を根拠に選ぶ練習' },
    { type: 'practice', title: '練習問題：答えだけでなく数え方も説明しよう', problems: [
      { body: '「有益な助言を二つもらった」のつもりで書いたI got two advices.を、piecesを使って直しましょう。', answer: '**I got two pieces of useful advice.** adviceは通常不可算なので、個別の内容をpiecesで数えます。元の英文には「有益な」がないため、usefulも加えます。' },
      { body: 'aかanを選びましょう：①___ hour ②___ useful tool。', answer: '**①an ②a**。hourはhを発音せず母音で始まります。usefulはつづりのuでなく、最初の「ユ」に近い子音に合わせてaを選びます。' },
      { body: '買い物前の質問です。How ___ apples do we need? / How ___ rice do we need?にmanyかmuchを入れましょう。', answer: '**many / much**。applesは個数を数える可算名詞の複数、riceは食材の量として扱う不可算名詞です。' },
      { body: '「コップ3杯の水」を英語で書きましょう。各杯を150 mLとすると合計は何mLですか。', answer: '**three glasses of water、450 mL**。複数になるのはglass。3 × 150 = 450で、waterは不可算のままです。各杯150 mLという条件があるので合計量も求まります。' },
      { body: 'Would you like some bread?を「疑問文なのにsomeだから誤り」とする説明は正しいですか。', answer: '**正しくありません。** パンを勧める申し出なのでsomeが自然です。breadはここでは不可算です。疑問文の形だけでanyに直す必要はありません。' },
      { body: 'I like coffee.と、店で言うTwo coffees, please.ではcoffeeの数え方がどう違いますか。', answer: '前者は飲み物一般を表す**不可算**。後者は注文する一杯分を単位にした**可算**です。後者はTwo cups of coffee, please.とも言えます。注文のcoffeesを根拠に、どんな場面でも複数形にできると考えてはいけません。' },
    ] },
    { type: 'quiz', title: '確認クイズ：指定された意味に合う一つを選ぼう', questions: [
      { question: '「リンゴがいくつ必要ですか」の空欄に入るのは？ How ___ apples do we need?', choices: ['much', 'many', 'a'], answerIndex: 1, explanation: 'applesは可算名詞の複数で、個数を尋ねるのでHow manyを使います。' },
      { question: '買ったばかりの一冊を初めて話題にします。I bought a book.の続きとして「その本はおもしろい」を表すのは？', choices: ['A book is interesting.', 'Book is interesting.', 'The book is interesting.'], answerIndex: 2, explanation: '買ったその本を相手が特定できるのでThe bookです。A bookでは同じ本を特定して指す表現になりません。' },
      { question: '「水をコップ二杯」を標準的な形で表すのは？', choices: ['two glasses of water', 'two glass of waters', 'two waters of glass'], answerIndex: 0, explanation: '数える単位glassをglassesにします。中身のwaterは不可算のままです。' },
      { question: '夕食についてWe ate chicken.と言ったとき、この文のchickenの基本的な解釈は？', choices: ['一羽の生きたニワトリを指す可算名詞', '鶏肉を表す不可算名詞', '必ず二羽以上を指す複数形'], answerIndex: 1, explanation: '食事の文脈で冠詞なしのchickenは通常、材料としての鶏肉を表します。動物を個体として数えるならa chickenやchickensなどとなります。' },
      { question: 'Would you like some tea?について正しい説明は？', choices: ['疑問文なのでsomeは必ず誤り', 'someの後ろは可算名詞だけなので誤り', 'お茶を勧める申し出なのでsomeが自然'], answerIndex: 2, explanation: 'someは不可算名詞にも使えます。申し出や依頼では、疑問文でもsomeが自然な場合があります。' },
    ] },
    { type: 'note', variant: 'tip', content: '迷ったら①この場面で何を指すか、②個体なら単数か複数か、③聞き手がどれか特定できるか、④個数か量か、⑤質問・否定・申し出など何をしたい文か、の順に確認しましょう。「単語ごとに一つの数え方」と決め付けず、意味と形を一緒に読むことが大切です。' },
  ],
};
