import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'je-conjunction-clauses',
  title: '接続詞で文をつなぐ：理由・条件・時・逆接を節で読む',
  summary: 'because・if・when・althoughを、単語の和訳ではなく二つの出来事の関係から選ぶ。主語と動詞を目印に節を区切り、語順・コンマ・未来の表し方を確かめて一文を組み立てる。',
  objectives: [
    '二つの主語と動詞を探し、主節と接続詞が導く従属節の範囲を示せる。',
    '理由・条件・時・予想に反する結果を区別して接続詞を選べる。',
    '接続詞を節ごと動かして、基本的な語順とコンマを整えられる。',
    '未来を表す時・条件の副詞節で、通常は現在形を使う理由と適用範囲を説明できる。',
  ],
  blocks: [
    { type: 'note', variant: 'info', content: 'この記事の英文・会話・設問はすべて学習用の自作です。主語＋動詞の基本文と現在形・過去形・willを学んだ人を対象に、標準的な英語の基本用法を扱います。ここでは主に、文の出来事に理由・条件・時などを添える「副詞節」を学びます。文学的な省略や仮定法は扱いません。' },
    { type: 'heading', level: 3, content: '1　二枚の出来事カードに「関係」を付ける' },
    { type: 'text', content: '「道がぬれていた」「私たちはゆっくり歩いた」と別々に言うだけでは、その関係を聞き手が推測する必要があります。「道がぬれていた**ので**」と結べば、ゆっくり歩いた理由だと伝わります。英語でも、The path was wet. と We walked slowly. の間にどんな関係があるかを接続詞で示せます。単に文を長くするための語ではありません。' },
    { type: 'text', content: 'We walked slowly because the path was wet.（道がぬれていたので、私たちはゆっくり歩いた。）では、becauseが「後ろの内容は理由です」という札になります。because the path was wetの全体が理由のカードで、becauseだけを前に移してよいわけではありません。まず「何を言いたいか」と「何を付け足すか」を分けましょう。' },
    { type: 'heading', level: 3, content: '2　節の境界は、主語と動詞から探す' },
    { type: 'text', content: 'ひとまとまりの主語・述語をもつ語のまとまりを**節**と呼びます。今回の基本文では、接続詞の後ろにも「主語＋動詞」があります。We walked slowlyは主語We・動詞walked、the path was wetは主語the path・動詞wasです。中心の内容を述べるWe walked slowlyが**主節**、becauseを含めて理由を添えるbecause the path was wetが**従属節**です。主節・従属節の区別は、文中の前後ではなく働きで決まります。' },
    { type: 'table', headers: ['切り分けた部分', '主語と動詞', 'この文での働き'], rows: [
      ['[We walked slowly]', 'We / walked', '主節：私たちはゆっくり歩いた'],
      ['[because the path was wet]', 'the path / was', '従属節：道がぬれていた、という理由'],
      ['because', '主語でも動詞でもない', '後ろの節を理由として主節に結ぶ接続詞'],
    ] },
    { type: 'note', variant: 'warn', content: 'because the rainだけでは、今回の「because＋主語＋動詞」の形になりません。「雨が降っていたので」ならbecause it was raining、「雨のために」ならbecause of the rainです。because ofの後ろは名詞のまとまりです。また、Because it was raining.だけでは通常の説明文として主節が欠けます。ただしWhy?への会話の返答では、このような省略も自然です。' },
    { type: 'list', ordered: true, items: [
      '二つの出来事をいったん独立した文にする。それぞれの主語と動詞に印を付ける。',
      '中心にしたい内容を主節にし、もう一方が理由・条件・時・逆接のどれかを考える。',
      '従属節に接続詞を付け、[接続詞＋主語＋動詞…]を一枚のカードとして囲む。',
      'カードを主節の前か後ろに置く。前置きなら節の終わりにコンマを置くのが基本。',
      '時制と語順を点検し、日本語で関係を言い直して、意図した意味か確かめる。',
    ] },
    { type: 'heading', level: 3, content: '3　becauseとalthough：同じ出来事でも関係が違う' },
    { type: 'text', content: 'becauseは「なぜ？」に答える理由を添えます。I took a taxi because I was tired.（疲れていたのでタクシーに乗った。）なら、疲れていることが行動の理由です。一方、疲れているなら普通は歩きたくない、と予想する場面でI walked home although I was tired.と言えば、「疲れていたけれど歩いて帰った」。althoughは、背景から予想される結果と実際の主節が食い違うことを示します。これを**譲歩（逆接）**と呼びます。' },
    { type: 'table', headers: ['接続詞', '読み取る問い', '注意する点'], rows: [
      ['because：〜なので', '主節の出来事が起きた理由は？', 'becauseの直後の節が理由。前にある節が必ず理由なのではない。'],
      ['although：〜だけれども', '普通の予想に反して、実際はどうだった？', '二つの事実が論理的に矛盾する必要はない。期待とのずれを表す。'],
    ] },
    { type: 'example', title: '例題1：理由の札はどちらに付ける？', body: 'The bus was late. / Mei missed the first song. をbecauseで結び、「バスが遅れたので、メイは最初の歌を聞き逃した」としましょう。理由の節を後ろに置く形と前に置く形を書きます。', answer: 'まず理由は「バスが遅れた」、伝えたい結果は「メイが聞き逃した」と判定します。後置き：Mei missed the first song because the bus was late. 前置き：Because the bus was late, Mei missed the first song. 移すのは[because the bus was late]全体です。両方とも主節の主語・動詞はMei / missed、理由の節はthe bus / wasで、基本的な理由関係は変わりません。' },
    { type: 'example', title: '例題2：理由でなく、予想とのずれを表す', body: '「その箱は小さかった。それでも、その中に本を十冊入れた」。The box was small. / I put ten books in it. をalthoughで一文にします。どちらをalthoughの後ろに置きますか。', answer: 'Although the box was small, I put ten books in it.（箱は小さかったけれど、私はその中に本を十冊入れた。）「小さい箱にはあまり入らなそうだ」という予想のもとになる背景がthe box was smallです。それをalthoughに続け、意外な結果を主節にします。箱の容量から十冊入ると計算したのではなく、話し手が実際の結果を述べた文です。becauseなら「小さかったことが入れた理由」となり、この意図とは違います。' },
    { type: 'note', variant: 'warn', content: '日本語の「〜なので、だから」「〜だけれど、でも」をそのまま二重にしないこと。今回の基本構文ではBecause the bus was late, so Mei missed the first song.とはせず、soを取ります。同様にAlthough the box was small, but I put ten books in it.ではbutを取ります。接続詞を重ねるのでなく、The box was small, but I put ten books in it.という別の組み立てもできます。' },
    { type: 'heading', level: 3, content: '4　ifとwhen：起きるかどうか、それとも起きる時か' },
    { type: 'text', content: '予定を立てるとき、「アヤが来る**なら**」と「アヤが来た**とき**」では前提が違います。If Aya comes, we will start the game.は、来るかどうかを未確定の条件として扱います。When Aya comes, we will start the game.は、来ることを見込んで、その時に何をするかを述べます。ifは分かれ道の条件札、whenは時間線上の目印だと考えると区別しやすくなります。' },
    { type: 'table', headers: ['形', '意味・場面', '読み取れる限界'], rows: [
      ['if＋主語＋動詞', 'もし〜なら：条件が成り立つ場合を述べる', 'その条件が実現したと断定しない。'],
      ['when＋主語＋動詞', '〜するとき／〜したとき：時を指定する', '未来の文では実現を見込むが、現実に必ず実現するという保証ではない。'],
    ] },
    { type: 'text', content: 'whenは未来だけの語ではありません。When I opened the door, the cat ran outside.（私がドアを開けたとき、猫が外へ走り出した。）なら、過去の二つの出来事を時の関係で結びます。主節はthe cat ran outside、時の節はwhen I opened the doorです。「whenを見たら現在形」と丸暗記せず、いつの出来事かを先に見ます。' },
    { type: 'example', title: '例題3：同じ英語の材料から予定の前提を変える', body: 'We will eat in the garden ___ the weather is fine tomorrow. の空欄にifとwhenを入れると、前提はどう変わりますか。「明日の天気はまだ分からない。晴れた場合だけ庭で食べる予定だ」に合う語を選びましょう。', answer: 'この場面ではifです。We will eat in the garden if the weather is fine tomorrow. は「明日晴れなら庭で食べる」。whenを入れると、晴れることを見込んでその時の行動を述べる読みになります。ただしifの英文一つだけから「晴れなければ絶対に庭で食べない」まで論理的に確定するわけではありません。今回は日本語の場面説明がその予定を補っています。' },
    { type: 'heading', level: 3, content: '5　節ごとの語順と未来の表し方を点検する' },
    { type: 'text', content: '接続詞は関係を示す札なので、それだけで疑問文の語順にはなりません。When does Aya arrive?は到着時刻を尋ねる独立した疑問文ですが、We will eat when Aya arrives.のwhenは時の節を導く接続詞です。その中はAya arrivesという普通の「主語＋動詞」の順です。主語が三人称単数なのでarrivesのsも残ります。' },
    { type: 'text', content: '未来の時・条件を表す副詞節では、通常、未来の出来事にも現在形を使います。When Aya arrives tomorrow, we will eat. / If it rains tomorrow, we will stay home. のように、時・条件の節は「その出来事が成立する場面」を指定し、主節がその場面での予定を述べます。英語ではこの役割分担のとき、副詞節に予測のwillを通常重ねません。arrivesやrainsが現在形でも、tomorrowや文全体から未来だと分かります。これは未来の表し方の文法上の決まりで、現在形ならいつでも未来になるという意味ではありません。' },
    { type: 'note', variant: 'warn', content: '「ifやwhenの後ろは絶対にwill禁止」ではありません。I do not know if Aya will come.（アヤが来るかどうか分からない。）のifは条件でなく「〜かどうか」という知りたい内容を導きます。I do not know when Aya will arrive.のwhenも「いつ着くか」という内容です。今回の時・条件の副詞節とは働きが違います。willが意志などを表す用法もあるため、このレッスンの規則は基本的な未来の時・条件に限って使いましょう。' },
    { type: 'table', headers: ['基本の並べ方', '自作例', '点検すること'], rows: [
      ['主節＋接続詞の節', 'We will stay home if it rains.', '後置きの短い条件節の前は、通常コンマなし。'],
      ['接続詞の節, 主節', 'If it rains, we will stay home.', '従属節全体を前に出し、その終わりにコンマ。'],
      ['過去の時の節, 過去の主節', 'When the bell rang, we closed our books.', 'rangもclosedも過去。未来の規則を当てはめない。'],
    ] },
    { type: 'note', variant: 'tip', content: '従属節の前置きは背景を先に示し、後置きは主節を先に伝える形です。基本的な関係は保てますが、情報の出し方や強調は変わります。コンマも常に一律ではなく、後置きのalthough節などでは対比や補足を示すため置くことがあります。まずは短い基本文の形を身に付けましょう。' },
    { type: 'example', title: '例題4：一つずつ直してから節を動かす', body: '「明日サキが来たとき、私たちはポスターを見せる」のつもりで書いたWe will show Saki the poster when will Saki come tomorrow.を直し、whenの節を前に移しましょう。', answer: '①中心はWe will show Saki the poster。②時の節の主語・動詞はSaki / come。疑問ではないので主語を先にし、未来の時の副詞節だからwillを取ります。③三人称単数の現在形はcomes。修正：We will show Saki the poster when Saki comes tomorrow. ④[when Saki comes tomorrow]全体を移して、When Saki comes tomorrow, we will show Saki the poster. となります。Sakiを繰り返したのは節の主語を見やすくするためです。' },
    { type: 'heading', level: 3, content: '6　関係を決めてから、一文を完成させる' },
    { type: 'practice', title: '練習：答えと一緒に判断の根拠を言おう', problems: [
      { body: 'I turned on the light because the room was dark.を二つの節に分け、それぞれの主語・動詞と主節を答えましょう。', answer: '[I turned on the light] / [because the room was dark]。主語・動詞はI / turned、the room / was。主節はI turned on the lightで、because以下が電気をつけた理由です。turned onは「つけた」というまとまりとして意味を取ります。' },
      { body: '「電車が止まったので、私たちはバスに乗った」。The train stopped. / We took a bus. をbecauseで結び、理由を先に書きましょう。', answer: 'Because the train stopped, we took a bus. 理由のThe train stoppedにbecauseを付け、その節全体を前に置きます。二つの出来事は過去なのでstopped / tookのままです。コンマの後ろにsoは不要です。' },
      { body: '「眠かったけれど、ユイは最後まで映画を見た」を表すため、Although Yui was sleepy, but she watched the whole movie.の不要な語を一つ取りましょう。', answer: 'butを取ってAlthough Yui was sleepy, she watched the whole movie.。althoughが、眠いなら途中でやめそうなのに最後まで見た、という予想とのずれを既に示しています。' },
      { body: '来られるかまだ不明の友人について「もしレンが来たら、一緒に昼食を食べよう」と言います。___ Ren comes, we will have lunch together.にifかwhenを入れ、理由を説明しましょう。', answer: 'If。来るかどうかを未確定の条件にしているからです。Whenなら来ることを見込んで、来た時の予定を述べる形になります。未来の条件なのでcomesは現在形で適切です。' },
      { body: '「明日授業が終わったとき、私はあなたに電話する」という予定です。I will call you when the class (ends / will end) tomorrow.から基本用法に合う方を選び、when節を前に出しましょう。', answer: 'endsを選び、When the class ends tomorrow, I will call you.。when節は未来の時を表す副詞節なので通常現在形。主語the classは三人称単数なのでendsです。節の終わりはtomorrowまでで、そこでコンマを置きます。' },
      { body: 'I do not know if Ken will join us.のwillを「ifの後ろだから」という理由だけで削除してよいですか。', answer: 'よくありません。ここは「ケンが加わるかどうか分からない」であり、if以下はknowの内容です。「もし加わるなら」という条件の副詞節ではありません。未来に加わるかを述べるwill joinは適切です。まずif節の働きを確認します。' },
    ] },
    { type: 'quiz', title: '確認クイズ：指定の意味に合う一つを選ぼう', questions: [
      { question: '「寒かったことが理由で窓を閉めた」と表す接続詞は？ I closed the window ___ it was cold.', choices: ['although', 'because', 'if'], answerIndex: 1, explanation: '理由を明示するのはbecauseです。althoughは寒いのに閉めたという予想とのずれ、ifは条件となり、指定された関係ではありません。' },
      { question: 'Although the bag was heavy, Hana carried it upstairs.の主節はどれ？', choices: ['Although the bag was heavy', 'the bag was heavyだけ', 'Hana carried it upstairs'], answerIndex: 2, explanation: '主節は、重さにもかかわらずハナが上へ運んだという中心の出来事です。althoughの付いた前半は、予想のもととなる背景を添える従属節です。' },
      { question: '「晴れるか未確定。もし明日晴れたら、私たちは外で練習する」に合う基本文は？', choices: ['If it is sunny tomorrow, we will practice outside.', 'Because it is sunny tomorrow, we will practice outside.', 'Although it is sunny tomorrow, we will practice outside.'], answerIndex: 0, explanation: '未確定の条件なのでifを選びます。未来の条件の副詞節では通常isという現在形を使い、主節にwill practiceを置きます。' },
      { question: '「トムが到着したときに話そう」という予定を、普通の語順と時制で表すのは？', choices: ['We will talk when does Tom arrive.', 'We will talk when Tom arrives.', 'We will talk when Tom arrive.'], answerIndex: 1, explanation: '接続詞whenの節は疑問文の語順にしません。主語Tomに続けて、未来の時の副詞節の現在形arrivesを置きます。三人称単数のsも必要です。' },
      { question: 'Because I was hungry, I made a sandwich.と同じ基本的な理由関係を保って節を並べ替えた文は？', choices: ['I was hungry because I made a sandwich.', 'Because I made a sandwich, I was hungry.', 'I made a sandwich because I was hungry.'], answerIndex: 2, explanation: '理由は「空腹だった」、結果は「サンドイッチを作った」です。[because I was hungry]を丸ごと後ろへ移すと関係を保てます。他の二つは作ったことを空腹の理由にしてしまいます。' },
    ] },
    { type: 'note', variant: 'tip', content: '最後の確認は「札・箱・中身」の順です。札＝接続詞は意図した関係か。箱＝接続詞の節を最後まで囲めるか。中身＝各節に必要な主語・動詞があり、語順と時制が合っているか。単語の和訳を先に埋めるのでなく、二つの出来事の関係を一言で説明してから英文に戻りましょう。' },
  ],
};
