import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'je-preposition-space',
  title: '前置詞の空間イメージ：in・on・at・to・forと時間表現',
  summary: '箱の中・面への接触・地図上の目印から前置詞を考える。同じ場所でも見方が変わる例を読み、目的地と受け手、時刻・日付・期間の表し方を、慣用表現の限界とともに整理する。',
  objectives: [
    'in・on・atを内部・接触・位置の目印というイメージで説明する。',
    'toの目的地・受け手と、forの行き先・受益者・期間を文全体から区別する。',
    '時刻・曜日や日付・月や年に合う前置詞と、前置詞を付けない時間表現を選ぶ。',
    '空間の比喩だけで判断できない語法を認め、動詞と前置詞の組合せで確認する。',
  ],
  blocks: [
    { type: 'note', variant: 'info', content: '例文・会話・問題はすべて学習用の自作です。標準的な日常英語の基本用法を扱います。「箱・面・点・矢印」は覚えるための比喩であり、英語のすべての用法を導く法則や語源の説明ではありません。慣用・地域差がある表現は、学習辞書で動詞と前置詞を一緒に確認しましょう。' },
    { type: 'heading', level: 3, content: '1　同じ「に」でも、見せたい関係が違う' },
    { type: 'text', content: '「かばんに」「机に」「入口に」は日本語では全部「に」です。しかし、かばんの内部にあるのか、机の表面に載っているのか、入口という目印の所にあるのかは違います。英語の前置詞はこの関係を示します。たとえばThe key is in my bag.（鍵はかばんの中）、The key is on the desk.（机の上）、I am at the entrance.（私は入口の所）と使い分けます。まず日本語の助詞でなく、物と場所の関係を思い描きましょう。' },
    { type: 'text', content: '**前置詞**は通常、名詞や代名詞などの前に置き、それとの関係を表す語です。in my bagは「前置詞＋名詞のまとまり」。This gift is for her.（この贈り物は彼女のためのもの）では、前置詞forの後ろの代名詞はsheでなく目的格herになります。前置詞一語でなく、後ろまでひとまとまりとして読みます。' },
    { type: 'heading', level: 3, content: '2　in・on・at：内部、接触、位置の目印' },
    { type: 'text', content: '探し物をするとき、袋を開けるのか、机の表面を見るのかで動作が変わります。この違いがinとonの入口です。一方、待ち合わせで「駅にいる」と言うときは駅の壁や床を説明する必要がありません。駅を地図上の目印として示すatが役立ちます。' },
    { type: 'table', headers: ['語', '基本イメージ', '自作例と読み方'], rows: [
      ['in', '領域・容器の内部', 'The gloves are in the box.（手袋は箱の中にある）'],
      ['on', '面に接している', 'The map is on the wall.（地図は壁に貼ってある）'],
      ['at', '場所を位置・活動の目印として示す', 'We met at the library.（図書館で会った）'],
    ] },
    { type: 'text', content: 'inの境界は箱の壁のように見えるとは限りません。I live in Osaka.は大阪という地域の内部に住むということです。onは必ずしも「上」ではなく、壁に貼った地図にも使います。at the libraryは図書館を会う場所として示し、建物内か玄関前かまでは決まりません。細かな位置が必要ならat the library entrance（図書館の入口で）などと付け足します。' },
    { type: 'example', title: '例題1：同じ図書館を二つの見方で伝える', body: '友人に①「図書館で会おう」、雨が降ってきたので②「今は図書館の建物の中にいる」と伝えたい。at / inを使って英文を作り、強調点を説明しましょう。', answer: '①Let’s meet at the library. ②I am in the library now. ①は図書館を待ち合わせの場所として示すat。②は建物の内部にいることを明示するinです。①でinを使って建物内で会うと指定することもできます。場所の名詞だけで唯一の前置詞が決まるのではなく、伝えたい関係で選びます。' },
    { type: 'note', variant: 'warn', content: '「小さい場所はat、大きい場所はin」は絶対の規則ではありません。広い空港も待ち合わせ地点ならat the airport、箱のような小さな物も内部ならin the boxです。またon the third floor（3階に）は階を一つの層として捉える表現です。実物の大きさだけで機械的に選ばないでください。' },
    { type: 'heading', level: 3, content: '3　toとfor：「どこへ」と「誰のために」を読む' },
    { type: 'text', content: '地図で学校までの道に矢印を引くと、矢印の先が目的地です。I am walking to school.（学校へ歩いている）のtoはその先を示します。ただし歩いている途中なので、もう着いたとは言っていません。**toは目的地を示すが、到着済みかは動詞や時制による**、と分けて考えましょう。' },
    { type: 'text', content: '物の受け渡しも矢印で描けます。I gave the notebook to Emi.（エミにノートを渡した）ではto Emiが受け手。一方、I bought a notebook for Emi.（エミのためにノートを買った）ではfor Emiが利益を受ける人です。買った段階ではまだ渡していなくても言えます。**toの受け手**と**forの受益者**は、日本語でどちらも「エミに」と訳せても同じ関係ではありません。' },
    { type: 'example', title: '例題2：買うことと渡すことを分ける', body: '兄のためにマフラーを買いましたが、まだ自分の部屋に置いてあります。I bought a scarf ___ my brother. をto / forから選びましょう。その後兄に手渡したなら、I gave the scarf ___ him. はどちらですか。', answer: '順にfor、to。購入は兄のためにした行動なのでfor my brother。手渡しでは物を受け取る相手を示すto himです。forだけで受け渡し完了を意味することはありません。動詞がbuyなのかgiveなのかを見て、名詞との関係を判断します。' },
    { type: 'text', content: 'forは行き先にも使います。The bus left for Sendai.（バスは仙台に向けて出発した）では出発時点の目的地を示します。ただし「toとforはいつでも交換できる」わけではありません。go to Sendai、leave for Sendai、arrive in Sendai、arrive at the stationのように、動詞と場所の捉え方に合った組合せで覚えます。arrive to Sendaiはこの意味の標準形ではありません。' },
    { type: 'note', variant: 'warn', content: '「toは必ず到着を表し、forは絶対に到着しない」は誤りです。walking to schoolは途中でも使え、left for Sendaiだけでは後で到着したか不明です。またgo homeのhomeは方向を表す副詞として使われるため、通常go to homeとはしません。go to schoolの形をそのまま全単語に当てはめないようにしましょう。' },
    { type: 'heading', level: 3, content: '4　時刻・日付・月：時間にも目印を置く' },
    { type: 'text', content: '予定表を想像しましょう。「7時」は時計の針が指す目印、「月曜日」はカレンダーの一枠、「5月」はその中に何日も含む期間です。atを点、onを日付の欄、inを期間の中、と結び付けると覚えやすくなります。ただしこれは用法を覚える比喩です。曜日が本当に平面だからonになる、と証明できるわけではありません。' },
    { type: 'table', headers: ['時間の種類', '基本形', '自作例'], rows: [
      ['時刻', 'at＋時刻', 'The lesson starts at seven.（授業は7時に始まる）'],
      ['曜日・日付', 'on＋曜日や日付', 'We practice on Tuesday. / We meet on May 10.'],
      ['月・年・季節', 'in＋月・年・季節', 'The event is in May. / Flowers bloom in spring.'],
      ['朝・午後・夕方', 'in the morning / afternoon / evening', 'I read in the evening.（夕方に読書する）'],
      ['特定の日の朝など', 'on Monday morningなど', 'We leave on Monday morning.（月曜の朝に出発する）'],
    ] },
    { type: 'example', title: '例題3：予定を広い枠から時刻へ絞る', body: '自作の予定表に「5月／5月10日／午前7時」とあります。The trip is ___ May. We leave ___ May 10 ___ seven in the morning. をin / on / atで埋めましょう。', answer: 'in、on、at。月という期間ならin May、日付ならon May 10、時刻ならat sevenです。さらに「5月10日の朝に」ならon the morning of May 10。in the morningの前に単に日付を足すのでなく、日を特定した形ではonにするのが基本です。' },
    { type: 'note', variant: 'warn', content: 'in the morningは「いつの朝か不明」のときだけではありません。文脈上翌朝だと分かっていても使えます。onになる基本形はon Monday morningやon the morning of May 10のように、表現自体で特定の日を示す場合です。また一般に「夜に」はat nightという慣用形。in the nightも「ある夜の間に」の意味などで使え、誤文とは限りません。' },
    { type: 'text', content: '「いつ」を一語・一まとまりで表せる場合には前置詞を付けないこともあります。We will meet tomorrow.（明日会おう）、I visited her last Sunday.（先週の日曜に訪ねた）、We will practice next Monday.（次の月曜に練習する）。tomorrowや、last・next・this・everyが付くこれらの時間表現には通常in / on / atを重ねません。on Mondayからon next Mondayを機械的に作らないことが大切です。' },
    { type: 'heading', level: 3, content: '5　for two hoursとin two hoursは何が違う？' },
    { type: 'text', content: '「2時間」は時刻でなく長さです。時間線に2時間分の帯を描き、その帯の間ずっと行った活動を述べるならforを使います。I studied for two hours.は「2時間勉強した」。一方、I will leave in two hours.は発話時点から2時間後の出発、I finished the puzzle in two hours.は完成までにかかった時間です。同じin two hoursでも、未来の開始か、完了した作業の所要時間かを文全体で見分けます。' },
    { type: 'example', title: '例題4：14時からの時間線で検算する', body: '①と②は別の場面です。①今は14時です。I will leave in two hours.の出発時刻は？ ②今は17時で、今日14時から16時までの勉強を振り返っています。I studied from two to four.の勉強時間をforを使って言い換えると？ それぞれの場面の時刻は同日の午後とします。', answer: '①14時＋2時間＝16時に出発します。2時間ずっと出発するという意味ではありません。②16時−14時＝2時間なのでI studied for two hours.です。from two to fourのtoは区間の終点、for two hoursは区間の長さを表します。時刻（14時・16時）と時間の長さ（2時間）を混同しないでください。' },
    { type: 'heading', level: 3, content: '6　イメージで選び切れない乗り物・慣用表現' },
    { type: 'text', content: 'バスも車も人を内部に乗せます。それでも普通の乗車表現はon the bus / train、in the car / taxiです。「大型は床の上、小型は箱の中」という覚え方は補助にはなりますが、必ず成り立つ規則ではありません。on a bike（自転車に乗って）やby bus（バスという交通手段で）のように、何を伝えるかと慣用の両方を確認します。' },
    { type: 'table', headers: ['言いたいこと', '基本表現', '注意'], rows: [
      ['バス・電車に乗っている', 'on the bus / on the train', 'inも内部を特に描写する文脈などでは可能。常に誤りとはしない'],
      ['車・タクシーに乗っている', 'in the car / in a taxi', '乗車位置を表す標準的な組合せ'],
      ['バスで通うという交通手段', 'by bus', 'この用法のbyの後ろは通常冠詞なし'],
      ['学校にいる／仕事中', 'at school / at work', '建物の一点だけでなく活動・所属する場を表す慣用もある'],
    ] },
    { type: 'note', variant: 'tip', content: '選ぶ順序は①何と何の関係か、②内部・接触・目印・目的地・受益者・時間のどれか、③動詞との組合せや慣用はどうか、です。「全部イメージで説明する」ことを目標にせず、イメージは候補を出す道具、用例は候補を確かめる道具として使い分けましょう。' },
    { type: 'practice', title: '練習：前置詞と根拠をセットで答える', problems: [
      { body: '手紙を封筒の内部に入れました。The letter is ___ the envelope. をin / on / atから選びましょう。', answer: 'in。封筒という容器の内部にあることを示します。onなら封筒の表面に載っている関係になります。' },
      { body: 'I bought flowers ___ my mother. / I gave the flowers ___ her. にto / forを入れましょう。', answer: 'for、to。buyでは母のために購入したという受益者、giveでは花を受け取る相手を示します。herは前置詞の後ろなので目的格です。' },
      { body: 'We will meet ___ Friday ___ nine. を埋めましょう。さらにFridayをnext Fridayにしたら、曜日の前はどうなりますか。', answer: 'on Friday、at nine。曜日はon、時刻はatです。next Fridayなら通常前置詞は不要で、We will meet next Friday at nine.となります。' },
      { body: '現在9時です。I will start in three hours.の開始時刻は？ その後12時から15時まで作業したとき、I worked ___ three hours.の空欄は？', answer: '9時＋3時間＝12時に開始。作業の長さは15時−12時＝3時間なのでforです。inはここでは今から後の開始時点、forは継続した時間の長さを表します。いずれも同日の時刻です。' },
      { body: '「私はバスで学校に通う」をI go to school ___ bus.と表しましょう。また「今バスに乗っている」はI am ___ the bus now.の通常の表現で答えましょう。', answer: 'by、on。by busは交通手段を冠詞なしで述べ、on the busは乗車している場を示します。「中だからin」とだけ考えず、用法の違いを見ます。' },
      { body: 'I am walking to the station.は「すでに駅に着いた」を必ず意味しますか。', answer: 'いいえ。toは駅を目的地として示しますが、am walkingは歩いている途中を述べています。到着の有無はto一語からは決められません。' },
    ] },
    { type: 'quiz', title: '確認クイズ：指定された意味に合うものを一つ選ぼう', questions: [
      { question: '「箱の内部にある」を表すのは？ The key is ___ the box.', choices: ['on', 'in', 'at'], answerIndex: 1, explanation: '内部という関係にはin。onでは箱の表面にある意味になります。' },
      { question: '標準的な形で「火曜日の朝に出発する」を表すのは？', choices: ['We leave at Tuesday morning.', 'We leave in Tuesday morning.', 'We leave on Tuesday morning.'], answerIndex: 2, explanation: '曜日を伴う特定の日の朝はon Tuesday morningです。in the morningをそのまま当てはめません。' },
      { question: '「妹のために昼食を作った」の空欄は？ I made lunch ___ my sister.', choices: ['for', 'to', 'at'], answerIndex: 0, explanation: '昼食を作る行為の受益者を示すのでforです。物の受け渡し先を表すgive lunch toとは動詞と関係が異なります。' },
      { question: '今10時です。「2時間後に出発する」を表すのは？', choices: ['I will leave for two hours.', 'I will leave in two hours.', 'I will leave at two hours.'], answerIndex: 1, explanation: '未来の出発が今から2時間後なのでin two hours。出発時刻は12時です。for two hoursなら不在にする期間などの解釈となり、同じ意味ではありません。' },
      { question: '前置詞のイメージについて正しい説明は？', choices: ['大きい場所には必ずinを使う', 'toがあれば到着済みと分かる', 'イメージは理解の補助で、動詞との組合せや慣用も確認する'], answerIndex: 2, explanation: 'at the airportのように広い場所もatで示せます。toは目的地を示しても到着済みとは限りません。比喩と用法の両方を使います。' },
    ] },
  ],
};
