import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'sch-solubility-product',
  title: '溶解度積と共通イオン効果：沈殿が始まる境界を計算する',
  summary: '「今の濃度の積」と「飽和の境界」を比べ、沈殿の有無を判断する。化学量論からモル溶解度を求め、共通イオンがあるときの濃度近似を自分で点検する。',
  objectives: [
    '溶解度積と反応商の違いを説明し、未飽和・飽和・過飽和を判定できる',
    '溶解反応の係数から、モル溶解度と各イオンの濃度を結び付けられる',
    '沈殿開始の境界と、沈殿生成後の平衡濃度を区別できる',
    '共通イオンを含む式を立て、近似後に無視した濃度の割合を確認できる',
  ],
  blocks: [
    { type: 'heading', level: 3, content: '1．「溶けきる量」は、相手のイオンにも左右される' },
    { type: 'text', content: '駅の改札で出る人と入る人が同時に動いていても、両方の人数がつり合えば構内の人数は変わりません。難溶性の塩と水溶液の境界でも、固体からイオンが離れる変化と、イオンが固体へ戻る変化が同時に起きます。両者がつり合うのが溶解平衡です。「溶けにくい」は「全く溶けない」ではありません。' },
    { type: 'note', variant: 'info', content: '以下はすべて架空の塩・架空の数値による紙上モデルです。実在物質の物性値や実験操作は扱いません。温度を一定とし、希薄な理想溶液として扱います。対象イオンの酸塩基反応・錯形成・他の沈殿生成はないものとします。対イオンは電気的中性を保ちますが、この溶解平衡には直接参加しないとします。' },
    { type: 'text', content: 'まず、架空の塩 MX が陽イオン M⁺ と陰イオン X⁻ に分かれる場合を考えます。濃度を表す角括弧は、水溶液中を自由に動くそのイオンのモル濃度です。固体を含めた全量でも、錯体に取り込まれた分まで足した濃度でもありません。' },
    { type: 'formula', tex: String.raw`\mathrm{MX(s)}\rightleftharpoons \mathrm{M^+(aq)}+\mathrm{X^-(aq)},\qquad K_{\mathrm{sp},c}=[\mathrm{M^+}]_{\mathrm{eq}}[\mathrm{X^-}]_{\mathrm{eq}}`, display: true },
    { type: 'text', content: '固体と飽和溶液が共存する平衡で、イオン濃度の積が一定になると考えます。これが濃度で表した**溶解度積**です。純粋な固体は量が増えても固体としての状態が同じなので、固体の質量をこの積に掛けません。ただし固体が残らず全部溶けた場合、必ず飽和するわけではありません。' },
    { type: 'note', variant: 'info', content: String.raw`本記事は濃度型を明示して $K_{\mathrm{sp},c}$ と書き、濃度の単位は mol/L に統一します。MX の濃度型溶解度積の単位は (mol/L)² です。厳密な熱力学的溶解度積は無次元の活量 $a_i=\gamma_i[i]/c^\circ$ で定義され、$c^\circ=1\,\mathrm{mol/L}$。ここでは活量係数 $\gamma_i\approx1$ とする近似です。濃い溶液では濃度の積だけで同じ精度の判定はできません。` },
    { type: 'heading', level: 3, content: '2．反応商 Q は「現在地」、溶解度積 K は「境界」' },
    { type: 'text', content: '改札のたとえでいえば、つり合った人数の条件と、今の人数は別物です。溶解度積は平衡の基準値ですが、反応商は平衡かどうかに関係なく、その時点の濃度から計算できます。この二つを比較するからこそ、これから固体ができる向きかどうかを判断できます。' },
    { type: 'formula', tex: String.raw`Q_c=[\mathrm{M^+}][\mathrm{X^-}]`, display: true },
    { type: 'table', headers: ['比較', '状態', 'このモデルで読み取れること'], rows: [
      ['Q_c < K_sp,c', '未飽和', '固体があれば溶ける向き。固体がなければ自動的にイオンが増えるわけではない'],
      ['Q_c = K_sp,c', '飽和の境界', '固体が共存すれば溶解平衡。等号だけから固体の量は決まらない'],
      ['Q_c > K_sp,c', '過飽和', '沈殿が生じる向きが有利。沈殿により自由なイオン濃度が下がる'],
    ] },
    { type: 'note', variant: 'warn', content: '「どんな溶液でも Q = K と置く」のは誤りです。未飽和なら Q < K のまま存在できます。また Q > K は沈殿生成の熱力学的な方向を示すのであって、目に見える固体が何秒後に現れるかを決める式ではありません。結晶の核ができるまで過飽和が続く場合もあり、本記事ではその速さは扱いません。' },
    { type: 'heading', level: 3, content: '3．モル溶解度から濃度へ：係数は二つの場所に効く' },
    { type: 'text', content: '一組の切符が「大人1枚・子ども2枚」なら、組数をそのまま子どもの枚数にはできません。溶解も同じで、塩が何 mol 溶けたかと、各イオンが何 mol 生じたかを反応式でつなぎます。**モル溶解度 s** は、その条件で飽和溶液1 L中に溶けている塩の物質量を表し、単位は mol/L です。' },
    { type: 'derivation', title: '対象イオンを初めに含まない水で、固体が残る場合', steps: [
      { label: '1：MX では1組から1個ずつ', tex: String.raw`[\mathrm{M^+}]=s,\quad [\mathrm{X^-}]=s,\quad K_{\mathrm{sp},c}=s^2`, note: '対象イオンの供給源は溶けた塩だけ、と仮定する。' },
      { label: '2：別の架空塩 MX₂ は1組から1個と2個', tex: String.raw`\mathrm{MX_2(s)}\rightleftharpoons\mathrm{M^{2+}}+2\mathrm{X^-},\quad [\mathrm{M^{2+}}]=s,\quad [\mathrm{X^-}]=2s`, note: 'ここでは M は2価の架空陽イオン。MX の1価イオンとは別のモデルである。' },
      { label: '3：係数2は反応商の指数にも現れる', tex: String.raw`K_{\mathrm{sp},c}=[\mathrm{M^{2+}}][\mathrm{X^-}]^2=s(2s)^2=4s^3`, note: 'MX₂ の濃度型溶解度積の単位は (mol/L)³。' },
    ] },
    { type: 'example', title: '例題1：同じ「溶解度」でも反応式から立て直す', body: String.raw`架空塩 MX の $K_{\mathrm{sp},c}=4.0\times10^{-10}\,(\mathrm{mol/L})^2$、別の架空塩 MX₂ の $K_{\mathrm{sp},c}=3.2\times10^{-11}\,(\mathrm{mol/L})^3$ とする。それぞれ対象イオンを初めに含まない水で固体と平衡にある。モル溶解度と陰イオン濃度を求めよう。`, answer: String.raw`MX は $s=\sqrt{4.0\times10^{-10}}=2.0\times10^{-5}\,\mathrm{mol/L}$ で、X⁻も同濃度。MX₂ は $4s^3=3.2\times10^{-11}$ より $s=2.0\times10^{-4}\,\mathrm{mol/L}$、X⁻は $2s=4.0\times10^{-4}\,\mathrm{mol/L}$。確かめると $(2.0\times10^{-4})(4.0\times10^{-4})^2=3.2\times10^{-11}$。` },
    { type: 'note', variant: 'warn', content: '溶解度積の数値が小さいほど必ずモル溶解度も小さい、とはいえません。反応式が違えば指数も濃度型の単位も異なります。例題1では、数値の小さい MX₂ のほうが s は大きくなりました。また s と、溶媒100 gあたりの質量で表す溶解度は別の量です。' },
    { type: 'heading', level: 3, content: '4．沈殿開始は、まだ沈殿で濃度が減っていない境界' },
    { type: 'text', content: '境界を求めるときは、「まだ沈殿ができていないと仮定した濃度」で Q を計算します。限りなく境界に近い状態では、沈殿によるイオンの減少はゼロに近づくからです。一方、境界を超えた後にできる沈殿の量を求めるなら、減ったイオンを引く必要があります。この二つを分けましょう。' },
    { type: 'formula', tex: String.raw`[\mathrm{X^-}]_{\mathrm{crit}}=\frac{K_{\mathrm{sp},c}}{[\mathrm{M^+}]_0}\qquad ([\mathrm{M^+}]_0>0)`, display: true },
    { type: 'text', content: '添字0は沈殿による消費前の濃度、critは境界を表します。この式では M⁺の濃度を指定値として固定しています。全体積が変わる設定なら、その変化を反映した濃度を使います。与えられた物質量を全体積で割ってから比較するのであって、別々の溶液の元の濃度をそのまま掛けるのではありません。' },
    { type: 'example', title: '例題2：三つの架空データを境界と比べる', body: String.raw`MX の $K_{\mathrm{sp},c}=4.0\times10^{-10}\,(\mathrm{mol/L})^2$。沈殿による消費前の M⁺濃度はいずれも $2.0\times10^{-4}\,\mathrm{mol/L}$ とする。X⁻濃度が① $1.0\times10^{-6}$、② $2.0\times10^{-6}$、③ $3.0\times10^{-6}\,\mathrm{mol/L}$ の三つの仮想状態を判定せよ。濃度はすべて同じ最終体積を基準とする。`, answer: String.raw`境界は $[\mathrm{X^-}]_{\mathrm{crit}}=(4.0\times10^{-10})/(2.0\times10^{-4})=2.0\times10^{-6}\,\mathrm{mol/L}$。①の Q は $2.0\times10^{-10}\,(\mathrm{mol/L})^2$ で未飽和、②は $4.0\times10^{-10}$ で飽和の境界、③は $6.0\times10^{-10}$ で沈殿生成が有利。②の等号だけでは有限量の沈殿が既にあるとはいえない。③の消費前濃度も沈殿後の平衡濃度ではない。` },
    { type: 'formula', tex: String.raw`([\mathrm{M^+}]_0-x)([\mathrm{X^-}]_0-x)=K_{\mathrm{sp},c},\qquad 0<x<\min\{[\mathrm{M^+}]_0,[\mathrm{X^-}]_0\}`, display: true },
    { type: 'text', content: '上の式は MX の沈殿が生じて固体と平衡になる場合の式です。x は一定体積の溶液1 Lあたり沈殿になった MX の mol 数で、単位は mol/L。1対1でイオンが消費されるので両方から同じ x を引きます。境界だけを問う問題に、この沈殿後の未知量を最初から持ち込む必要はありません。' },
    { type: 'heading', level: 3, content: '5．共通イオン効果：積を保つなら片方が増えると他方は減る' },
    { type: 'text', content: '長方形の面積を一定にして横を長くすれば、縦は短くなります。同様に、MX の溶解平衡で X⁻が別の供給源から既に存在すると、一定の濃度積に達するまでに必要な M⁺は少なくなります。これが共通イオン効果でモル溶解度が小さくなる理由です。温度一定なので、変わったのは K ではなく平衡濃度です。' },
    { type: 'derivation', title: '「もともとの X⁻」と「MX から増える X⁻」を分ける', steps: [
      { label: '濃度収支', tex: String.raw`[\mathrm{M^+}]=s,\qquad [\mathrm{X^-}]=c+s`, note: '初めに M⁺はなく X⁻は c mol/L 存在する。体積変化は無視し、固体が残る平衡を考える。s は溶けた MX の濃度。' },
      { label: 'まず近似しない式', tex: String.raw`s(c+s)=K_{\mathrm{sp},c}`, note: '同じイオンは供給源を区別せず、濃度を足す。' },
      { label: 's が c より十分小さいと仮定', tex: String.raw`c+s\approx c\quad\Longrightarrow\quad s_{\mathrm{app}}=\frac{K_{\mathrm{sp},c}}{c}`, note: 'M⁺の濃度 s 自体をゼロにする近似ではない。' },
      { label: '計算後に自己点検', tex: String.raw`\frac{s_{\mathrm{app}}}{c}=\frac{K_{\mathrm{sp},c}}{c^2}\ll1`, note: '例えばこの比が0.01以下かを目安にする。1%という目安は自然法則ではなく、必要な精度に応じて選ぶ。' },
    ] },
    { type: 'example', title: '例題3：近似は「小さそう」ではなく比で確かめる', body: String.raw`MX の $K_{\mathrm{sp},c}=4.0\times10^{-10}\,(\mathrm{mol/L})^2$。初めの X⁻濃度 $c=2.0\times10^{-3}\,\mathrm{mol/L}$、M⁺は初めに存在せず、固体が残る平衡での s を求める。体積変化は無視する。`, answer: String.raw`まず $s(c+s)=K_{\mathrm{sp},c}$。近似すると $s_{\mathrm{app}}=2.0\times10^{-7}\,\mathrm{mol/L}$。比は $s_{\mathrm{app}}/c=1.0\times10^{-4}=0.010\%$ と小さい。厳密な正の解は約 $1.9998\times10^{-7}\,\mathrm{mol/L}$ で、近似値とよく一致する。対象イオンを初めに含まない場合の $2.0\times10^{-5}\,\mathrm{mol/L}$ の約100分の1であり、共通イオンが溶解を抑えている。` },
    { type: 'formula', tex: String.raw`s=\frac{-c+\sqrt{c^2+4K_{\mathrm{sp},c}}}{2}=\frac{2K_{\mathrm{sp},c}}{c+\sqrt{c^2+4K_{\mathrm{sp},c}}}`, display: true },
    { type: 'text', content: '近似が不十分なら二次方程式の正の解を使います。負の解は濃度として不適切です。右端の形は分子を有理化した同じ式で、非常に近い数同士の引き算を避けられます。c = 0なら s = √K へ戻るので、対象イオンを初めに含まない場合ともつながります。' },
    { type: 'note', variant: 'warn', content: String.raw`同じ K でも $c=2.0\times10^{-5}\,\mathrm{mol/L}$ なら、近似値は $s_{\mathrm{app}}=2.0\times10^{-5}\,\mathrm{mol/L}$。比が1なので $c+s\approx c$ は使えません。正の解は約 $1.236\times10^{-5}\,\mathrm{mol/L}$ です。「難溶性だからいつでも s を無視できる」のではなく、比較相手 c に対して小さいかが重要です。` },
    { type: 'heading', level: 3, content: '6．自分で解くときの道筋' },
    { type: 'list', ordered: true, items: [
      '溶解反応式を書き、各イオンが何個ずつ生じるかを確認する。',
      '濃度の基準体積と単位を確認し、初めに存在するイオンを区別する。',
      '沈殿の判定なら消費前の Q と K を比べる。境界なら Q = K と置く。',
      '溶解度なら固体が残る条件を確認し、濃度を s や c + s で表す。',
      '近似を使ったら無視した項の比を調べ、元の式への代入でも確かめる。',
    ] },
    { type: 'practice', title: '練習：答えより先に濃度の式を書こう', problems: [
      { body: String.raw`架空塩 MX₂ の $K_{\mathrm{sp},c}=4.0\times10^{-12}\,(\mathrm{mol/L})^3$。対象イオンを初めに含まない水で固体と平衡にあるときの s と X⁻濃度は？`, hint: 'X⁻の濃度にも反応商の指数にも、係数2が関係する。', answer: String.raw`$4s^3=4.0\times10^{-12}$ より $s=1.0\times10^{-4}\,\mathrm{mol/L}$。X⁻は $2.0\times10^{-4}\,\mathrm{mol/L}$。積に戻すと $(1.0\times10^{-4})(2.0\times10^{-4})^2=4.0\times10^{-12}$。` },
      { body: String.raw`架空塩 MX の $K_{\mathrm{sp},c}=4.0\times10^{-10}\,(\mathrm{mol/L})^2$。沈殿による消費前の M⁺濃度を $5.0\times10^{-4}\,\mathrm{mol/L}$ に固定したとき、X⁻の境界濃度は？ X⁻が $4.0\times10^{-7}\,\mathrm{mol/L}$ ならどの状態か。`, answer: String.raw`境界は $8.0\times10^{-7}\,\mathrm{mol/L}$。指定状態の Q は $2.0\times10^{-10}\,(\mathrm{mol/L})^2<K_{\mathrm{sp},c}$ なので未飽和。境界より小さいことからも確認できる。` },
      { body: String.raw`架空塩 MX の $K_{\mathrm{sp},c}=4.0\times10^{-10}\,(\mathrm{mol/L})^2$。初めに M⁺はなく、X⁻濃度は $c=2.0\times10^{-4}\,\mathrm{mol/L}$。体積一定で固体と平衡にあるとき、近似した s と比 $s_{\mathrm{app}}/c$ を求めよ。`, answer: String.raw`$s(c+s)=K_{\mathrm{sp},c}$ から $s_{\mathrm{app}}=K_{\mathrm{sp},c}/c=2.0\times10^{-6}\,\mathrm{mol/L}$。比は0.010、つまり1.0%。本記事の1%目安では境目に当たる。正の解は約 $1.9804\times10^{-6}\,\mathrm{mol/L}$ で、近似値は約0.99%大きい。より高い精度が必要なら正の解を使う。` },
      { body: String.raw`架空塩 MX の $K_{\mathrm{sp},c}=4.0\times10^{-10}\,(\mathrm{mol/L})^2$。一定体積での消費前濃度が M⁺、X⁻とも $3.0\times10^{-5}\,\mathrm{mol/L}$ だった。沈殿が生じて平衡に達したとき、溶液1 Lあたり沈殿になった MX の量 x は？`, answer: String.raw`初めの Q は $9.0\times10^{-10}\,(\mathrm{mol/L})^2$ で K より大きい。$(3.0\times10^{-5}-x)^2=4.0\times10^{-10}$。残る濃度は正なので $3.0\times10^{-5}-x=2.0\times10^{-5}$、よって $x=1.0\times10^{-5}\,\mathrm{mol/L}$。境界判定に使った初めの濃度とは異なる。` },
    ] },
    { type: 'quiz', title: '確認クイズ：式を使う条件を選ぶ', questions: [
      { question: 'この理想溶液モデルで Q_c < K_sp,c、対象の固体は存在しない。この情報からいえるのは？', choices: ['未飽和であり、沈殿生成は有利ではない', '必ず溶解が起き、イオンが自動的に増える', '必ず固体と平衡にある'], answerIndex: 0, explanation: '比較は未飽和を示す。固体がなければそこから溶け出すことはできず、必ず Q = K になるわけではない。' },
      { question: '温度一定の希薄理想溶液で MX に対する共通イオン X⁻が既に存在する。変わらないものは？', choices: ['MX のモル溶解度', 'X⁻の平衡濃度', '濃度型溶解度積'], answerIndex: 2, explanation: '同じ温度・同じモデルでは K は変わらず、s と各イオンの平衡濃度が変わる。活量の影響を無視できる条件付きの説明である。' },
      { question: 'c + s ≈ c という近似を採用した後、直接確かめるべき量は？', choices: ['s の数値が1より小さいかだけ', 's/c が必要な精度に対して十分小さいか', '固体の質量と c の数値が等しいか'], answerIndex: 1, explanation: '単位のある s の数値だけでは小ささを決められない。無視した項と残した項の無次元比で点検する。' },
      { question: '沈殿開始の境界として Q_c = K_sp,c が得られた。必ずいえるのは？', choices: ['有限量の沈殿が既に見えている', 'すべてのイオンが消費された', '指定した濃度が飽和条件を満たす'], answerIndex: 2, explanation: '等号は飽和の条件であり、固体の量や生成速度は与えない。固体が共存していれば溶解平衡となる。' },
    ] },
    { type: 'note', variant: 'info', content: '根拠と適用範囲：溶解反応に対する質量作用の法則と、反応式に基づく物質量収支から式を導きました。数値は学習用に設定した架空値で、物性表の引用ではありません。温度変化、活量係数の変化、錯形成や酸塩基反応を含む実際の溶液へ、そのまま数値を転用することはできません。' },
  ],
};
