import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'se-articles-reference',
  title: '冠詞と指示：初出・共有情報・一般化のa／the／無冠詞',
  summary: '冠詞を「初出ならa、二度目ならthe」という暗記から、読み手と情報を共有する仕組みへ発展させる。話し手の知識と聞き手の知識、推論による特定、一般化と特定集団の違いを、短い段落の読み書きで学ぶ。',
  objectives: [
    '話し手が対象を知っていることと、聞き手が対象を特定できることを区別する。',
    '初出のtheや、同じ名詞が再登場してもaを使う理由を文脈から説明する。',
    '無冠詞複数・不可算名詞、a単数、the単数による一般化の違いと限界を理解する。',
    '指示対象の連鎖をたどり、意図した一般論や特定の出来事に合う英文を作る。',
  ],
  blocks: [
    { type: 'note', variant: 'info', content: '英語例文・会話・段落・設問と訳はすべて学習用の自作です。標準的な英語の通常の文を対象にし、見出し・固有名詞・地域差のある慣用表現は主題にしません。可算・不可算やa／anの音による区別は中学記事「数え方で意味が変わる英語」で学んだものとし、本記事では数量表現でなく、文章内の情報共有と一般化を中心に扱います。' },
    { type: 'heading', level: 3, content: '1　冠詞は、聞き手の頭の中の「名札」を案内する' },
    { type: 'text', content: '友達に「先生に会った」と言うとき、自分には誰か分かっていても、友達には分からないことがあります。英語で I met a teacher yesterday. と言うのは、その先生を話し手が知らないからではありません。聞き手がどの先生か特定できる前提を置かず、一人の先生を話題に導入しているからです。**話し手が知っていることと、二人で共有していることは違う**のです。' },
    { type: 'text', content: 'I met a teacher yesterday. The teacher asked about our club.（昨日先生に一人会った。その先生は私たちの部活動について尋ねた。）では、最初の文で聞き手の頭の中に「昨日会った先生」という名札ができます。次のthe teacherは、その名札をたどれば対象が分かると示します。これは同じ話し手が続けて話しても成立します。冠詞は、話し手の交代ではなく**聞き手が対象を取り出せるか**に関わる仕組みです。' },
    { type: 'table', headers: ['基本の形', '聞き手への案内', '確認すること'], rows: [
      ['a／an + 可算単数', '一つの成員として提示する。どれか特定できるとは前提にしない', '特定の一人を話し手が知っていても使える'],
      ['the + 単数・複数・不可算', '文脈内で対象や対象の集合を特定できると見込む', '前の文・場面・共有知識などに根拠があるか'],
      ['無冠詞 + 複数・不可算', 'theによる特定をせずに述べる', '一般論か、特定しないいくつか／いくらかの話かは文全体で判断する'],
    ] },
    { type: 'note', variant: 'warn', content: '「aは話し手も知らないもの」「無冠詞は必ず一般論」はどちらも誤りです。I bought books yesterday.（昨日本を買った。）のbooksは、無冠詞複数でも昨日の具体的な出来事に登場する本です。Books can be expensive.（本は高価なことがある。）では一般論です。冠詞だけでなく、述語や時を示す表現も読みましょう。' },
    { type: 'heading', level: 3, content: '2　初出・再登場よりも「同じ対象か」を確かめる' },
    { type: 'text', content: 'なぜ「二度目ならthe」では足りないのでしょうか。名詞が同じでも、指す物が変わるからです。I bought a notebook on Monday. I bought a notebook on Friday, too.（月曜にノートを一冊買った。金曜にも一冊買った。）では、普通は別々の購入を述べています。二度目のnotebookもaで導入できます。一方、I bought a notebook. The notebook has a blue cover.なら、買ったその一冊の性質を続けて説明しています。単語の出現回数でなく、**どの対象へ矢印が戻るか**を考えます。' },
    { type: 'example', title: '例題1：話し手には分かる先生を導入する', body: '話し手は先生の名前を知っていますが、聞き手はその先生に会ったことがなく、まだ説明も受けていません。その先生を初めて導入し、次の文でも同じ人を指します。I spoke to ___ teacher after class. ___ teacher suggested a new topic. にa／theを入れ、話し手が名前を知っていてもよいか説明しましょう。', answer: '**a／The**。最初は「一人の先生」として導入し、聞き手がどれか特定できるとは前提にしないのでa。次は「授業後に話した先生」という名札ができているのでTheです。話し手が名前を知っていても問題ありません。聞き手の情報状態が根拠です。' },
    { type: 'heading', level: 3, content: '3　初出のthe：目の前・推論・説明から共有する' },
    { type: 'text', content: '初めて出る名詞にtheが付くのは、文章の外にも「どれか」を決める手掛かりがあるからです。一つだけの窓が開いている部屋で Please close the window. と言えば、前にwindowを言わなくても聞き手は対象を見つけられます。ただし窓がいくつもあり、どれも同じ状態なら、その文だけでは不十分かもしれません。唯一性は世界全体でなく、**その場の関連する範囲**で考えます。' },
    { type: 'table', headers: ['特定の手掛かり', '自作例文と場面', '何を共有しているか'], rows: [
      ['先に述べた対象', 'I found a key. The key was bent.', '見つけたその鍵'],
      ['目の前の状況', 'Please close the window.（窓が一つの部屋）', '開いている一つの窓'],
      ['関連からの推論', 'We entered a small theater. The stage was empty.', 'その劇場には中心となる舞台が一つあるという想定'],
      ['説明による限定', 'The notebook that I lent you is on the shelf.（貸したノートは一冊）', '貸したという出来事から一冊に絞れる'],
      ['共有された予定', 'The meeting starts at three.（二人が同じ会議を予定している）', '今日参加する、双方が承知した会議'],
    ] },
    { type: 'text', content: '劇場の例ではstageは初出ですが、theaterから「その劇場の舞台」を推論できます。このように、直接同じ名詞を繰り返さずに関連する対象へ進むこともあります。ただし劇場内に複数の舞台があると分かっているなら、どの舞台か説明を足す必要があるかもしれません。theは推論を促しますが、現実に必ず一つであることを保証する記号ではありません。' },
    { type: 'note', variant: 'warn', content: '「後ろにof句・関係節があれば必ずthe」ではありません。I need a book about stars.（星についての本が一冊必要だ。）では、about starsで種類を絞っても候補は多数あります。a book that explains this rule clearly（この規則を分かりやすく説明する本を一冊）も可能です。修飾語があることと、聞き手が対象を特定できることを分けましょう。' },
    { type: 'example', title: '例題2：舞台は初出なのになぜtheか', body: '次の自作段落では、劇場は初めて話題になります。客席から見える主な舞台は一つだと想定します。We visited ___ small theater. ___ stage was empty. A guide showed us ___ room behind the stage. 劇場と部屋は未紹介のものとして導入し、舞台は劇場との関連から特定するとき、a／theを選びましょう。', answer: '**a／The／a**。劇場は一つの訪問先として導入するのでa。stageは初出でも「訪問した劇場の主な舞台」と推論できるのでThe。部屋はbehind the stageという説明があっても、どの部屋かを共有済みとはしていないのでaです。なお最後のthe stageは、直前で述べた舞台を再び指しています。' },
    { type: 'heading', level: 3, content: '4　一般化：その場の物でなく種類の性質を述べる' },
    { type: 'text', content: '「昨日見た自転車」から「自転車という乗り物」へ話を広げるとき、個体を特定する必要がなくなります。Bicycles need regular maintenance.（自転車には定期的な整備が必要だ。）の無冠詞複数は、自転車一般を話題にしています。Knowledge grows through discussion.（知識は話し合いを通して深まる。）の無冠詞不可算も、ある一まとまりの知識を指さず、概念について述べています。' },
    { type: 'text', content: 'a単数にも一般化があります。A bicycle needs regular maintenance.では、一台を代表として取り上げ、自転車というものに当てはまる性質を述べます。I repaired a bicycle yesterday.なら昨日の一台を導入しています。同じa bicycleでも、**性質の説明か、一回の出来事の報告か**によって読みが違うのです。複数無冠詞とa単数は共に性質や規則を述べられ、「性質は必ず複数、規則は必ずa」と分けることはできません。' },
    { type: 'table', headers: ['形', '自作例文', 'この文での読み'], rows: [
      ['無冠詞複数', 'Bicycles need regular maintenance.', '自転車一般の性質'],
      ['a単数', 'A bicycle needs regular maintenance.', '典型的な一台を通した一般化'],
      ['無冠詞不可算', 'Knowledge grows through discussion.', '知識という概念についての一般論'],
      ['the複数', 'The bicycles in our shed need repairs.', '私たちの物置にある、特定できる自転車の集合'],
      ['the不可算', 'The knowledge I gained helped me.', '自分が得た、その知識'],
    ] },
    { type: 'note', variant: 'warn', content: '一般化は数学の「例外なくすべて」と同じではありません。Birds fly. のような一般文は、典型的な性質を述べるため、飛ばない鳥がいることだけで文法的に誤りにはなりません。一方、作文で All birds fly. と書けば「すべて」と明示した主張になります。冠詞や複数形だけで主張の強さを決めず、all・most・canなども見ましょう。' },
    { type: 'heading', level: 3, content: '5　theでも種類全体を表せる：一般化の限界を知る' },
    { type: 'text', content: 'theは特定の個体だけでなく、よく認識された種類を一つのまとまりとして扱うこともあります。The bicycle is an efficient means of transport.（自転車は効率的な交通手段だ。）では、ある一台でなく「自転車という乗り物」を指す読みが自然です。この種類を表すthe単数は、発明・動物の種などについての説明文でよく使われます。日常の作文で一般論を作るなら、まず無冠詞複数を考えると扱いやすいでしょう。' },
    { type: 'text', content: 'ただし三つの型はいつでも交換できません。The dodo is extinct.（ドードーは絶滅している。）は、ドードーという種全体についての文です。a単数は一羽の代表を取り上げますが、一羽は「死ぬ」のであって、一羽だけで種として「絶滅する」のではありません。そのため A dodo is extinct. は種の絶滅を述べる通常の表現として不適切です。逆に、一台の整備の必要性なら代表個体にも当てはまるのでa単数の一般化ができます。' },
    { type: 'note', variant: 'info', content: 'ドードーの英文も自作です。ここでは英語のextinctが種などの集団の消滅に関わることを説明するための例で、絶滅年代や原因についての資料読解は行いません。歴史的な数値・統計は扱いません。一般化のthe単数には語や文脈による自然さの差があるため、どんな名詞にも機械的に広げないでください。' },
    { type: 'example', title: '例題3：特定集団と一般論を読み分ける', body: '①Students need feedback. ②The students in this workshop need feedback. ③A student needs feedback. は、誰についての文ですか。①と③を一般的な学習上の主張として読む場合を考え、②との違いを説明しましょう。', answer: '①は生徒一般、③は一人の典型的な生徒を代表とした一般化です。②は「この講習会の生徒たち」という特定集団です。②だけから、あらゆる生徒についての主張を読み取ることはできません。また①・③の一般論も、各状況で例外なく全員に当てはまると明示するallの文とは異なります。' },
    { type: 'heading', level: 3, content: '6　段落で確かめる：対象を導入し、受け、一般化する' },
    { type: 'text', content: '自作段落を読みます。I borrowed a camera for our project. The camera was easy to use. Cameras can help students record changes over time.（企画のためにカメラを一台借りた。そのカメラは使いやすかった。カメラは生徒が時間の経過による変化を記録するのに役立つことがある。）一文目は一台の導入、二文目はその一台への参照、三文目はカメラ一般への拡張です。三文目をThe camerasにすると、複数の特定カメラを想定させますが、ここでは一台しか導入しておらず、別の説明が必要になります。' },
    { type: 'list', ordered: true, items: [
      'まず述語と場面を読む。個別の出来事か、一般的な性質か。',
      '個別の話なら、対象を聞き手が取り出せる根拠を探す。前の文・共有の場面・関連からの推論・限定の説明のどれか。',
      '特定できる対象や集団ならthe。特定を前提にしない可算単数ならa／an。複数・不可算なら無冠詞やsomeなども候補になる。',
      '一般論なら無冠詞複数・不可算を基本に検討する。a単数の代表個体に言える性質か、the単数で種類を述べる表現かも確かめる。',
      '最後に形を確認する。通常の文の可算単数を裸にせず、my cameraやthis cameraにはa／theを重ねない。',
    ] },
    { type: 'practice', title: '練習：根拠を言葉にしよう', problems: [
      { body: '話し手は昨日会った画家の名前を知っていますが、聞き手はその人を初めて知ります。I met a painter yesterday. のaは誤りですか。', answer: '誤りではありません。話し手が誰か知っていても、聞き手が特定できるとは前提にせず、一人を導入するならa painterです。' },
      { body: '全員が一つの会議を予定している状況で、会話の最初にThe meeting starts at three.と言えますか。', answer: '言えます。双方が予定している会議を特定できるので、初出でもtheを使えます。会議が複数あって判別できないなら説明を補います。' },
      { body: 'I need a book that explains this rule clearly. は関係節が付いているので必ずthe bookに直すべきですか。', answer: 'いいえ。規則を分かりやすく説明する本ならどれか一冊でよい、という読みができます。関係節は候補の種類を絞りますが、一冊を特定するとは限りません。' },
      { body: '①I bought books yesterday. ②Books can be useful gifts. のbooksはどちらも一般論ですか。', answer: '①は昨日の購入という出来事に登場した本で、種類全体についての一般論ではありません。②は本一般についての性質です。無冠詞複数だけで一般論と決めず、文全体を読みます。' },
      { body: 'Cameras can be useful in class. と The cameras in this cupboard are broken. の対象の範囲を比べましょう。', answer: '前者はカメラ一般についての可能性、後者はこの戸棚にある特定のカメラの集合についての報告です。後者からカメラ一般が壊れているとは言えません。' },
      { body: '一人を代表とするa単数で「生徒にはフィードバックが必要だ」を書きましょう。', answer: 'A student needs feedback. 一人の生徒を典型として、一般的な必要性を述べます。Students need feedback.という無冠詞複数の型も可能です。' },
    ] },
    { type: 'quiz', title: '確認クイズ：指定した文脈に合う一つを選ぶ', questions: [
      { question: 'I borrowed a camera.に続けて「借りたそのカメラは重かった」と同一対象を明示するのは？', choices: ['The camera was heavy.', 'A camera was heavy.', 'Camera was heavy.'], answerIndex: 0, explanation: '借りた一台という名札を聞き手が使えるのでThe cameraです。aでは同一対象を特定して指す意味を明示できず、裸の可算単数も通常の文では不可です。' },
      { question: 'I need a tool that can open this box.について正しい説明は？', choices: ['関係節があるのでtheにしなければならない', '箱を開けられる道具なら一つでよいという読みができる', 'aなので話し手はtoolの意味を知らない'], answerIndex: 1, explanation: '関係節があっても候補を一つに特定するとは限りません。a toolは条件に合う一つとして提示できます。' },
      { question: 'I bought flowers yesterday.のflowersについて正しい説明は？', choices: ['無冠詞なので必ず花全般の性質の説明だ', '無冠詞の複数形は誤りだ', '昨日の出来事の花であり、無冠詞でも一般論とは限らない'], answerIndex: 2, explanation: '過去の購入の報告です。無冠詞複数が一般的な性質を述べるかどうかは文全体で判断します。' },
      { question: '一般的な生徒でなく「この講習会の特定の生徒たち」が主語なのは？', choices: ['Students need feedback.', 'The students in this workshop need feedback.', 'A student needs feedback.'], answerIndex: 1, explanation: 'The students in this workshopは文脈内で特定できる集団です。ほかの二つはこの設問では生徒一般についての文として読めます。' },
      { question: '種についてのThe dodo is extinct.を、同じ一般論としてA dodo is extinct.にそのまま交換しにくい理由は？', choices: ['aは動物には付けられないから', 'theは過去を表すから', '絶滅は一羽の典型ではなく種全体に関わる性質だから'], answerIndex: 2, explanation: 'a dodo自体は一羽のドードーを表す正しい名詞句です。しかし一羽が死ぬことと種が絶滅することは異なるため、一般化の型を機械的に交換できません。' },
    ] },
    { type: 'note', variant: 'tip', content: '読み終わったら自分で三文を書きましょう。①a単数で物を導入、②theで同じ物を受ける、③無冠詞複数でその種類の一般的な性質を述べる。その後、③にtheを付けると何を特定することになるか考えてください。冠詞を付ける練習から、読者の頭にどの対象を作り、いつ種類全体へ話を広げるかを設計する練習へ進めます。' },
  ],
};
