import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'se-modal-nuance',
  title: '助動詞の推量と義務——文脈と時点で読み分ける',
  summary: 'must を「義務」と決めつけず、根拠・規則・時点から判断する。must have、cannot have、should have の違いと、否定が及ぶ範囲を自作英文で学ぶ。',
  objectives: [
    'must・should の推量と義務・助言を、前後の文を根拠に区別できる',
    'must not・do not have to・cannot の否定の意味を説明できる',
    '過去の義務 had to と、過去についての推量 must have＋過去分詞を使い分けられる',
    'should have＋過去分詞が後悔・非難か、完了しているはずという期待かを判断できる',
  ],
  blocks: [
    { type: 'heading', level: 3, content: '1．助動詞は「事実」への話し手の態度を加える' },
    { type: 'text', content: '本記事の英文・会話・場面設定はすべて学習用の自作です。助動詞を読むときは、「何が起きたか」と「話し手がそれをどう捉えているか」を分けましょう。推量は、証拠などをもとに事態の可能性を判断する用法。義務・助言は、人に求められる行動を示す用法です。同じ must でも、前者なら「〜に違いない」、後者なら「〜しなければならない」となります。' },
    { type: 'example', title: '例題1：同じ must be here でも意味が変わる', body: 'A：The meeting starts at nine. All members must be here by then.\nB：I can hear Yuna laughing in the next room. She must be here.\nそれぞれの must を訳し分け、根拠を挙げよう。', answer: 'A：「会議は9時に始まる。全員それまでにここにいなければならない」。開始時刻に合わせた集合の要求なので義務です。B：「隣の部屋でユナが笑っているのが聞こえる。彼女はここにいるに違いない」。声という証拠から所在を判断しているので推量です。be の後ろが場所だから推量、と形だけでは決められません。' },
    { type: 'table', headers: ['見る観点', '義務・助言の読みを支えるもの', '推量・期待の読みを支えるもの'], rows: [
      ['前後の情報', '規則、締切、話し手からの指示', '観察した証拠、予定、通常の成り行き'],
      ['発言の目的', '相手や自分の行動を求める', '起きていること・起きたことを説明する'],
      ['訳したときの確認', '「する必要がある／した方がよい」が合うか', '「そうだろう／そうに違いない」が合うか'],
    ] },
    { type: 'note', variant: 'warn', content: 'must は必ず100％、may は必ず50％という確率表にはできません。推量の強さは話し手の確信であり、客観的な発生確率ではありません。また、主語が人なら義務、物なら推量とも限りません。The door must remain closed. は、規則を示す文脈なら「扉は閉めておかなければならない」です。' },
    { type: 'heading', level: 3, content: '2．否定すると「禁止」と「不要」が分かれる' },
    { type: 'table', headers: ['表現', 'この用法での意味', '自作例文'], rows: [
      ['must not（義務の否定形）', '〜してはいけない：禁止', 'You must not write on these cards.（このカードに書き込んではいけない）'],
      ['do not have to', '〜する必要はない：義務がない', 'You do not have to bring your own cards.（自分のカードを持参する必要はない）'],
      ['cannot / can\'t（否定の推量）', '〜のはずがない', 'This cannot be my card; mine is blue.（これは私のカードのはずがない。私のは青い）'],
      ['may not（推量）', '〜でないかもしれない', 'The shop may not be open today.（今日は店が開いていないかもしれない）'],
    ] },
    { type: 'text', content: '「必要がある」の否定は、必ずしも「しない必要がある」ではありません。do not have to は行動の義務を取り除くだけで、しても構いません。一方、must not は規則・指示の文脈では行動を禁止します。否定の推量には cannot を基本として押さえますが、cannot には能力不足や禁止、may not には不許可の用法もあります。助動詞一語だけでなく、証拠を述べているのか指示しているのかを確認してください。' },
    { type: 'note', variant: 'info', content: 'must not が常に禁止とは限りません。例えば The room is dark. They must not be at home. は、明かりを根拠に「留守に違いない」と推量する読みが可能です。この用法には地域・文体による使われ方の差もあります。「〜のはずがない」を表す基本形 cannot と、「〜でないに違いない」という must not の読みを、文脈なしに同一視しないようにしましょう。' },
    { type: 'example', title: '例題2：案内の否定を正確に読む', body: 'You do not have to print the map. You must not leave printed maps on the floor.\n「地図を印刷してはいけない」という案内だろうか。', answer: 'いいえ。「地図を印刷する必要はありません。印刷した地図を床に放置してはいけません」です。第1文は印刷の義務を否定するだけで、印刷そのものは禁止していません。第2文で禁止されるのは床に放置する行為です。' },
    { type: 'heading', level: 3, content: '3．過去の義務と、過去についての推量' },
    { type: 'text', content: '助動詞の直後は原形です。過去について推量するときの基本形は「助動詞＋have＋過去分詞」。have は原形のままで、主語が三人称単数でも has にはしません。ここで大切なのは、推量を行う時点と、推量の対象となる出来事の時点を分けることです。今ある証拠から昨日を振り返るなら must have left のように表します。' },
    { type: 'table', headers: ['形', '意味', '時点と注意'], rows: [
      ['must be / must leave', '今いるに違いない／出なければならない、など', '原形だから現在だけとは限らない。文脈で時点と用法を決める'],
      ['had to leave', '出なければならなかった', '過去に義務・必要があった'],
      ['must have left', '出発したに違いない', '典型的には、先行する出来事についての強い推量'],
      ['cannot have left', '出発したはずがない', '先行する出来事の可能性を強く否定する推量'],
      ['may / might have left', '出発したかもしれない', '先行する出来事の可能性を述べる'],
    ] },
    { type: 'example', title: '例題3：must have を過去の義務と訳さない', body: 'A：The hall closed early yesterday, so we had to leave at five.\nB：The hall is empty now, and Riku\'s coat is gone. He must have left already.\n出る「必要」を述べるのはどちらか。また、Bは実際の退場を目撃した文か。', answer: '必要を述べるのはA。「昨日はホールが早く閉まったので、私たちは5時に出なければならなかった」です。Bは「今はホールが空で、リクのコートもなくなっている。彼はもう帰ったに違いない」。現在の状況から、それより前の出発を推量しています。must have left は退場を目撃したという報告ではなく、証拠にもとづく結論です。' },
    { type: 'example', title: '例題4：cannot have の根拠を探す', body: 'The only bus to the village left at eight. Sora reached the bus stop at eight thirty. He cannot have caught that bus.\n最後の文を訳し、否定の推量を支える時刻関係を説明しよう。', answer: '「彼がそのバスに乗れたはずがない」。バスの出発は8時、ソラがその停留所に着いたのは8時30分で、到着が30分遅いためです。本文の設定ではそのバスが出発したことが前提です。「バスに乗ってはいけなかった」という過去の禁止ではありません。' },
    { type: 'note', variant: 'tip', content: 'have＋過去分詞を見たら機械的に「昨日」と考えず、基準時より前に完了することもあると押さえます。例えば Applicants must have completed the course before they apply. は、応募条件を示す文脈なら「応募前にその講座を修了していなければならない」。未来の応募時までの修了を要求する用法です。本記事の過去推量の例とは文脈が異なります。' },
    { type: 'heading', level: 3, content: '4．should have は後悔だけではない' },
    { type: 'text', content: 'should は助言・望ましさの「〜した方がよい」だけでなく、予定や通常の成り行きからの「〜のはずだ」という期待も表します。should have＋過去分詞も同様です。すでに失敗が分かっている場面では「〜すべきだったのに」という後悔・非難。結果をまだ確認していない場面では「もう〜しているはずだ」という期待になります。形だけで「実際にはしなかった」と断定できません。' },
    { type: 'example', title: '例題5：後続文で変わる should have', body: 'A：I should have checked the room number. I went to the wrong room.\nB：Aya left an hour ago, and the walk takes only ten minutes. She should have arrived by now, but I have not heard from her yet.\nshould have の意味を、それぞれ説明しよう。', answer: 'A：「部屋番号を確認しておくべきだった。違う部屋に行ってしまった」。失敗を振り返る後悔で、この文脈では十分に確認しなかったと読みます。B：「アヤは1時間前に出発し、徒歩では10分しかかからない。もう着いているはずだが、まだ連絡はない」。所要時間にもとづく期待で、到着したかは未確認です。「到着すべきだったのに実際には着かなかった」とは断定できません。' },
    { type: 'text', content: 'should not have＋過去分詞も、失敗を振り返る文脈では「〜すべきではなかったのに」となります。I should not have deleted that note. Now I need it. は「そのメモを削除すべきではなかった。今必要なのに」。削除してしまったことを後悔しています。ただし should have 全体の意味は期待の用法も含め、前後の情報で判断します。' },
    { type: 'heading', level: 3, content: '5．読解での判断手順' },
    { type: 'list', ordered: true, items: [
      '助動詞と動詞部分を分ける。must have left なら must が強い判断、have left が先行する出来事を示す。',
      '規則・指示なのか、証拠からの結論なのか、望ましさの評価なのかを確認する。',
      'yesterday・by now などと前後の出来事から、対象となる時点を決める。',
      '否定の対象を確かめる。「禁止」「不要」「不可能という推量」を区別する。',
      '本文で確認済みの事実と、話し手の推量・期待を分けて訳す。判断材料が足りなければ複数の読みを残す。',
    ] },
    { type: 'practice', title: '練習：訳だけでなく根拠も答える', problems: [
      { body: 'All visitors must show a ticket at the entrance. この must は何を表すか。', answer: '義務。「来場者は全員、入口でチケットを見せなければならない」。全員に対する入場時の手続きの要求であり、チケットを見せているに違いないという観察結果ではありません。' },
      { body: 'We had to carry the boxes upstairs yesterday. を訳し、「運んだに違いない」と言いたい場合は had to carry をどう変えるか。', answer: '「私たちは昨日、箱を上階へ運ばなければならなかった」。過去の義務・必要です。過去の推量にするなら must have carried。「運ばなければならなかった」と「運んだに違いない」は別の主張です。' },
      { body: 'You do not have to join the discussion. は参加禁止か。理由とともに答えよ。', answer: '参加禁止ではありません。「議論に参加する必要はない」で、参加の義務がないだけです。禁止なら、規則・指示の文脈で You must not join the discussion. などとします。' },
      { body: 'I should have saved a copy. Now I have lost the only file. を訳し、should have が期待ではなく後悔と読める根拠を述べよ。', answer: '「コピーを保存しておくべきだった。今、唯一のファイルを失ってしまった」。唯一のファイルを失ったという失敗から、コピーを保存しておかなかったことを振り返っています。' },
      { body: 'The package should have arrived by now. この一文だけで「荷物は届かなかった」と断定できるか。', answer: 'できません。「荷物は今頃もう届いているはずだ」という期待の読みが可能です。予定どおりなら完了しているとの判断で、実際の到着・未到着は前後の情報を確認する必要があります。' },
    ] },
    { type: 'quiz', title: '確認クイズ：文脈から一つ選ぶ', questions: [
      { question: 'The light is on in Mei\'s room, and I can hear her voice. She must be home. の must の意味は？', choices: ['帰宅する義務がある', '家にいるに違いない', '家にいてはいけない'], answerIndex: 1, explanation: '明かりと声を証拠として現在の所在を推量しています。家にいるよう指示する文ではありません。' },
      { question: '「昨日は鍵を返す必要があった」と過去の義務を述べる文は？', choices: ['I had to return the key yesterday.', 'I must have returned the key yesterday.', 'I cannot have returned the key yesterday.'], answerIndex: 0, explanation: 'had to が過去の義務・必要。must have returned は「返したに違いない」、cannot have returned は「返したはずがない」という過去についての推量です。' },
      { question: 'The sealed envelope is still on my desk. I cannot have mailed it yesterday. 最後の文の意味は？', choices: ['昨日それを郵送してはいけなかった', '昨日それを郵送する必要はなかった', '昨日それを郵送したはずがない'], answerIndex: 2, explanation: 'その封筒が机に残っていることを証拠に、昨日の郵送という出来事を否定する推量です。禁止や義務の不在ではありません。' },
      { question: 'I should not have thrown away the receipt. I need it for a refund now. の内容に合うものは？', choices: ['レシートを捨てておくべきだった', 'レシートを捨てるべきではなかったのに、捨ててしまった', 'レシートはまだ捨てられていないはずだと期待している'], answerIndex: 1, explanation: '返金のために今必要なのに捨ててしまった、という後悔です。失敗を振り返る文脈で should not have thrown away を読みます。' },
      { question: '「もう届いているはずだ」という期待の用法を明確に支える後続文は？ The message should have reached him by now. ___', choices: ['He usually gets messages immediately, but I have not checked with him yet.', 'I regret never sending it.', 'Do not send any messages.'], answerIndex: 0, explanation: '普段はすぐ受信するという根拠と、まだ本人に確認していないという情報が、完了の期待を支えます。到着していない事実や後悔を示す文ではありません。' },
    ] },
    { type: 'note', variant: 'tip', content: 'まとめ：must を見たら「必要か、推量か」、have＋過去分詞を見たら「どの基準時より前か」、should have を見たら「未実行への評価か、完了への期待か」を問います。日本語訳を一つ暗記するだけでなく、その訳を選ぶ証拠を英文から一つ挙げられることを目標にしましょう。' },
  ],
};
