import type { Lesson } from '../types.ts';

const modelA = 'Our school should provide a board for lending books. This would help students find books without buying them. For example, a student could post the title of a novel and borrow it from a classmate. Some students may worry that borrowed books will not be returned. However, a simple record of names and dates could reduce this risk. Therefore, I suggest trying the board in one class before offering it to the whole school.';
const modelB = 'Students should exchange comments before submitting an essay. A reader can notice unclear ideas that the writer has missed. For example, a classmate could ask what a vague word like "this" refers to. Although reading another essay takes time, a short checklist can keep the task focused. Students can check only the main claim and one supporting example. This limited exchange would help writers revise their work without requiring a long discussion.';

export const lesson: Lesson = {
  id: 'se-paragraph-writing',
  title: '段落英作文を設計する：主張・理由・具体例・譲歩と推敲',
  summary: '一つの主張を理由と具体例で支え、反対意見への譲歩を加える段落作文。自作の74語・72語モデルを文ごとに分析し、論理・文法・語数の順で改善する。',
  objectives: [
    '主張、理由、具体例、譲歩と応答の役割を区別し、一段落の設計図を作れる',
    '接続表現の意味と文法上の働きを区別し、文の断片や接続の誤りを直せる',
    '具体例の関連性と主張の範囲を確かめ、裏付けのない断定を避けられる',
    '決められた規則で語数と字数を検算し、必要な内容を残して推敲できる',
  ],
  blocks: [
    { type: 'heading', level: 3, content: '1　一段落で何を達成するか' },
    { type: 'text', content: '意見段落は、難しい単語を並べる場所ではなく、**一つの提案がなぜ妥当かを読者に説明する場所**です。このレッスンでは「学校生活を改善する提案を、理由・具体例・懸念への応答を含めて英語70〜80語で書く」という自作課題を使います。読解の目印を探すだけでなく、実際に書いて削り、論理が残っているか確かめます。' },
    { type: 'note', variant: 'info', content: 'この教材の英語例文・設問・モデル・日本語要約はすべて自作です。学校の施策や効果についての調査結果ではありません。could や would を用いた効果は、提案の下で想定する可能性であり、実測した事実ではありません。採点基準や数え方が別に指定されている試験では、その指定を優先してください。' },
    { type: 'heading', level: 3, content: '2　接続語より先に、文の仕事を決める' },
    { type: 'table', headers: ['文の仕事', '書く前に答える問い', '注意点'], rows: [
      ['主張', '誰が、何をするべきか', 'School life should be better. だけでは提案が特定できない'],
      ['理由', 'それをすると、なぜよいのか', 'It is a good idea. は主張の言い換えで、理由には足りない'],
      ['具体例', 'どんな場面で、その利点が生じるか', '具体的でも、理由と無関係な体験談なら支えにならない'],
      ['譲歩', 'もっともな懸念は何か', '反対意見を極端にして簡単に否定しない'],
      ['応答', '懸念をどう減らすか、どの条件なら勧められるか', '欠点を完全に消せないなら、範囲を絞る'],
      ['結び', '以上を踏まえ、何を提案するか', '説明していない新しい大きな利点を持ち込まない'],
    ] },
    { type: 'text', content: 'これは六つの「仕事」であり、必ず六文に分ける規則ではありません。一文で理由と例を表したり、譲歩と応答を合わせたりできます。短い段落なら結びを主張の繰り返しにせず、試行範囲などを明確にする文にすると有効です。課題が二つの理由を要求するなら、その条件に合わせて設計し直します。' },
    { type: 'heading', level: 3, content: '3　例題1：主張を限定し、具体例とつなぐ' },
    { type: 'example', title: '例題1：貸し借り用の掲示板を提案する', body: '自作課題：学校生活を改善する提案を70〜80語で書く。「本を貸し借りする掲示板」を題材とし、本を買わずに見つけられる利点、貸し出した本が返らない懸念、その対策を入れよう。まず日本語で主張の範囲を決めよう。', answer: '設計例：本の貸し借りを掲示板で仲介する → 買わずに読みたい本を見つけやすい → 小説の題名を掲示して級友から借りる → 返却されない懸念 → 名前と日付を記録する → まず一クラスで試す。最後を全校での即時導入にしないことで、対策の効果が未確認である点も踏まえた提案になる。' },
    { type: 'text', content: modelA },
    { type: 'table', headers: ['文', '語数', '役割とつながり'], rows: [
      ['Our school ... books.', '9', '主張：貸し借りのための掲示板を設ける'],
      ['This would ... them.', '9', '理由：買わずに本を見つけられる。This は掲示板を設ける提案を受ける'],
      ['For example, ... classmate.', '17', '具体例：題名を掲示し、級友から借りる場面を示す'],
      ['Some students ... returned.', '11', '譲歩：返却されないかもしれないという懸念を提示する'],
      ['However, ... risk.', '12', '応答：記録によってリスクを減らせる可能性を述べる'],
      ['Therefore, ... school.', '16', '結び：まず一クラスで試すという、条件を絞った提案'],
    ] },
    { type: 'text', content: '語数は 9 + 9 + 17 + 11 + 12 + 16 = 74語で、70〜80語の条件内です。this risk は「借りた本が返されないリスク」、it は「掲示板」を指します。指示語を直前の名詞と機械的に結び付けず、意味のつながりを確かめます。記録があれば必ず返却されるとまではいえないため、could reduce を使い、eliminate（なくす）とはしていません。' },
    { type: 'note', variant: 'tip', content: '具体例が支えるのは「本を買わずに見つけられる」という限定した利点です。この一例だけで「全員の読解力が上がる」「学校の費用が必ず下がる」とは結論できません。提案に説得力を持たせるには、効果を大きく言うより、理由と例の対応を正確にします。' },
    { type: 'heading', level: 3, content: '4　接続表現の意味と、つなぎ方を分ける' },
    { type: 'table', headers: ['表現', '自作の正しい形', '文法と役割'], rows: [
      ['because', 'The board may help because students can borrow books.', '理由を表す従属節を作る。理由節だけでは、通常の意見作文の独立した一文としては未完成'],
      ['for example', 'A reader can find unclear ideas. For example, a reader can ask what "this" means.', '前の一般的説明を具体化する。前の主張を証明する万能な語ではない'],
      ['although', 'Although the task takes time, it can help writers.', '譲歩を表す従属節と主節を組み合わせる。この構造にさらに but を足さない'],
      ['but', 'The task takes time, but it can help writers.', '等位接続詞として二つの節をつなぐ'],
      ['however', 'The task takes time. However, it can help writers.', '文副詞として対照を示す。独立節どうしをコンマだけでつなぐ働きはない'],
    ] },
    { type: 'example', title: '小例題：二つの接続ミスを直す', body: '自作の誤文を修正し、理由を述べよう。① Although the task takes time, but it can help writers. ② The task takes time, however, it can help writers.', answer: '① but を除いて Although the task takes time, it can help writers. とする。または Although を除いて The task takes time, but it can help writers. とする。② The task takes time. However, it can help writers. と二文にする。セミコロンを用いて The task takes time; however, it can help writers. とする形も可能。意味が逆接でも、although・but・however は同じ文法部品ではない。' },
    { type: 'heading', level: 3, content: '5　例題2：弱い下書きを、実行可能な提案にする' },
    { type: 'example', title: '例題2：添削前の段落のどこが弱いか', body: '自作の下書き：Students should exchange comments. It is good. For example, my friend likes English. Although it takes time, but everyone will write perfect essays.\n\n課題は例題1と同じ70〜80語。語数を増やすだけで十分か。理由・例・譲歩後の応答を改善しよう。', answer: '十分ではない。It is good. は利点の説明にならず、友人が英語を好きなことも、相互コメントが役立つ理由を示していない。Although ... but ... の接続を直し、全員が完璧に書けるという裏付けのない断定を除く。「書き手が見落とす不明点を読者が発見する」理由、「this の指示内容を尋ねる」例、「確認項目を絞って時間を抑える」応答に替える。' },
    { type: 'text', content: modelB },
    { type: 'table', headers: ['文', '語数', '改善した点'], rows: [
      ['Students should ... essay.', '8', '提出前にコメントを交換するという場面を限定'],
      ['A reader ... missed.', '11', '読み手と書き手の視点の差を理由にする'],
      ['For example, ... to.', '14', '曖昧な指示語を尋ねるという、理由に対応する具体例'],
      ['Although ... focused.', '14', '時間の負担を認め、チェックリストという対策へつなぐ'],
      ['Students can ... example.', '11', '確認対象を主張と一つの例に絞り、対策を具体化'],
      ['This limited ... discussion.', '14', '長い話し合いを要しない、限定した交換の価値を述べる'],
    ] },
    { type: 'text', content: '8 + 11 + 14 + 14 + 11 + 14 = 72語です。Although の節は欠点を認めますが、主節は立場を撤回せず、時間を抑える方法を示しています。第五文は無関係な二つ目の理由ではなく、チェックリストの中身の説明です。末尾の This limited exchange は、その範囲を絞った交換を受けます。「理由の数」だけでなく、必要な説明が足りているかで文を増減します。' },
    { type: 'heading', level: 3, content: '6　語数・字数は別の単位で数える' },
    { type: 'text', content: '本教材では、英文は前後の空白を除き、空白で区切った各まとまりを1語と数えます。句読点や引用符は独立した語にしません。For example, は2語、"this" は1語です。短縮形やハイフン語の扱いは試験によって違うため、上のモデルにはそれらを使っていません。字数は語数ではなく文字の数です。以下の英文字数は引用用の外側のかぎ括弧・見出し・改行を含めず、本文中の句読点と引用符を含めます。モデルの単語間は半角空白1字です。' },
    { type: 'table', headers: ['対象', '語数', '空白を含む英文字数', '空白を除く英文字数'], rows: [
      ['モデルA（貸し借り用掲示板）', '74', '421', '348'],
      ['モデルB（作文コメント交換）', '72', '450', '379'],
    ] },
    { type: 'text', content: 'モデルAでは語の間の空白が73字なので 348 + 73 = 421字、モデルBでは71字なので 379 + 71 = 450字です。語数が少ないモデルBの方が文字数は多くなっています。「80語」を「80字」と取り違えないでください。日本語で構想をまとめる場合も数え方を明示します。自作の要約「本を貸し借りする掲示板を一クラスで試し、記録を付けて返却忘れを減らす。」は、外側のかぎ括弧を除き、読点・句点を各1字として35字です。この要約は構想メモであり、英語の理由と例をすべて訳したものではありません。' },
    { type: 'heading', level: 3, content: '7　推敲の順序：内容を直してから数え直す' },
    { type: 'list', ordered: true, items: [
      '設問：賛否、理由の数、語数、段落数など、要求された条件に答えているか。',
      '論理：理由に「なぜ」、例に「どんな場面で」の答えがあるか。譲歩後に、対策または限定した結論があるか。',
      '一貫性：途中から別の提案になっていないか。指示語の中身を具体的な名詞句で言えるか。',
      '英文：各文の主語・動詞、単数複数、時制、because の断片、although と but の重複、however 前の句読点を確認する。',
      '圧縮と検算：曖昧な強調や重複から削る。重要な理由や具体例を消して語数だけ合わせない。最後の変更後に、文別の数を足し直す。',
    ] },
    { type: 'practice', title: '改善する練習：解答は一例、理由も説明する', problems: [
      { body: '自作下書き Students should exchange comments. It is good. の第二文を、読者の視点が役立つことを示す理由に替えよう。', answer: '例：A reader can notice unclear ideas that the writer has missed. 読者は書き手が見落とした不明点に気付ける、という仕組みを示している。good の言い換えではなく、コメント交換が役立つ理由になっている。' },
      { body: '「読者が不明点を発見する」という理由を支える例として、A My friend likes English. と B A classmate could ask what "this" refers to. のどちらを残すか。', answer: 'B。this が何を指すかという不明点を読者が指摘する場面であり、理由に直接対応する。A は具体的な人物に触れていても、コメントの効果との関係が示されていない。' },
      { body: '自作の誤文 Because students can borrow books. The board may help. を、理由と主張がつながる一文に直そう。', answer: '例：The board may help because students can borrow books. または Because students can borrow books, the board may help. because 節に主節をつなぐ。会話の短い返答とは異なり、この段落課題では Because 節だけを一つの完結した文にしない。' },
      { body: '自作文 Some students may worry that borrowed books will not be returned. の後に、主張を維持しながら懸念へ応答する文を作ろう。「必ず返る」と断定しないこと。', answer: '例：However, a simple record of names and dates could reduce this risk. 心配そのものを否定せず、記録という対策と、減らせる可能性を述べる。could reduce は全件返却の保証ではない。' },
      { body: 'モデルBを内容の役割を変えずに1語だけ短くし、語数を答えよう。削る語を具体的に示すこと。', answer: '例：第四文の a short checklist から short を削り、a checklist とする。第五文が確認対象を二点に限定しているので、短さの説明は残る。第四文は14語から13語となり、段落は72 − 1 = 71語。Although だけを消すと文のつなぎ方の修正が必要になるため、同じ操作にはならない。' },
    ] },
    { type: 'quiz', title: '確認クイズ：役割・接続・数え方', questions: [
      { question: 'モデルAの Some students may worry ... returned. の主な役割はどれか。', choices: ['提案に対する懸念を認める', '掲示板の費用を報告する', '記録の有効性を実証する', '提案を全面的に撤回する'], answerIndex: 0, explanation: '返却されない可能性に触れる譲歩であり、続く記録の提案につながる。費用や調査結果は述べておらず、掲示板をやめる結論にもなっていない。' },
      { question: '通常の意見作文で、文のつなぎ方が正しいものはどれか。', choices: ['Although the task takes time, but it can help writers.', 'The task takes time, however, it can help writers.', 'Although the task takes time, it can help writers.', 'Because the task takes time.'], answerIndex: 2, explanation: 'although 節と主節が一組になっている。第一選択肢は although と but の重複、第二は独立節をコンマだけでつなぐ誤り、第四は主節のない断片。' },
      { question: 'モデルBの具体例が理由を支えているのはなぜか。', choices: ['英語が好きな人の数を示したから', '読者が不明な指示語を尋ねる場面を示したから', '全員の作文が完璧になると証明したから', 'For example があればどんな内容でも根拠になるから'], answerIndex: 1, explanation: '不明点に読者が気付く、という一般的な理由を、this の指示内容への質問として具体化している。例示表現だけで無関係な内容が根拠に変わるわけではない。' },
      { question: 'この教材の規則で、For example, a reader can ask what "this" means. は何語か。', choices: ['8語', '9語', '10語', '11語'], answerIndex: 1, explanation: 'For / example, / a / reader / can / ask / what / "this" / means. の9語。コンマ・引用符・ピリオドは独立した語に数えない。' },
      { question: 'モデルAの結論として、本文の根拠から最も無理のないものはどれか。', choices: ['すべての本が必ず返却される', '全校生徒の成績が必ず向上する', '掲示板はどの学校でも費用がかからない', 'まず一クラスで掲示板を試すことを提案する'], answerIndex: 3, explanation: '貸し借りの利点と返却への懸念を踏まえ、試行範囲を限定するのが本文の結論。成績、費用、全件返却を保証する根拠はない。' },
    ] },
  ],
};
