import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'se-tense-aspect',
  title: '時制と相の読み分け——基準時・完了・進行と物語の時間',
  summary: '動詞の形を日本語訳に直結させず、「いつから見るか」「途中か、そこまでを振り返るか」を分ける。自作の短い物語を時間線に並べ、過去完了・完了進行形・未来完了を読み解く。',
  objectives: [
    '発話時・基準時・出来事の時間を区別して、時間関係を説明できる',
    '進行形が示す途中の場面と、完了形が示す基準時までのつながりを読み分けられる',
    '物語の過去形・過去進行形・過去完了形から、主筋・背景・回想を整理できる',
    '現在完了進行形や未来完了形を、文脈と基準時にもとづいて解釈できる',
  ],
  blocks: [
    { type: 'heading', level: 3, content: '1．動詞は「時計」と「カメラ」を持つ' },
    { type: 'text', content: '動画を見返すとき、「昨日の8時の場面を開く」ことと、「作業の途中を見るか、ある時点までの道のりを振り返るか」は別の操作です。英語の動詞にも、この二つの見方があります。時制は主に時間上の位置を、相（aspect）は出来事の内部や広がりをどう見るかを示します。本記事の英文・物語・時刻設定はすべて学習用の自作です。中学の基本形を前提に、形の暗記よりも文章中の視点移動に焦点を当てます。' },
    { type: 'text', content: 'まず三つを区別します。発話時は「語っている今」、基準時は「その場面を見る足場」、出来事の時間は「動作や状態が実際に成り立つ時間」です。I was drawing a map at eight last night.（昨夜8時には地図を描いていた）なら、今から昨夜8時へ足場を移し、その時刻を含む作業の途中を見ています。昨夜8時に描き始めたとも、その時刻に描き終えたとも述べていません。' },
    { type: 'table', headers: ['観点', '上の文での位置', '自分にする問い'], rows: [
      ['発話時', 'この文を話している今', 'いつ語っているか'],
      ['基準時', '昨夜8時', 'いつの場面にカメラを置くか'],
      ['出来事の時間', '地図を描く作業が続いていた時間帯', 'その場面で途中か、そこまでに起きたことか'],
    ] },
    { type: 'note', variant: 'info', content: 'ここでは完了も相の一種として整理します。英語学では完了の分類に異なる立場もあります。また「未来時制」は学校文法で便利な名称ですが、英語には過去形のような専用の未来語尾はありません。will などの助動詞や現在形も未来を表します。形の名前と実際に指す時間を同一視しないことが大切です。本記事では主に事実の報告・予測を扱い、仮定法や丁寧さを示す過去形は別に考えます。' },
    { type: 'heading', level: 3, content: '2．進行形は、終点を写さず途中へ入る' },
    { type: 'text', content: '料理中の一枚の写真だけでは、その料理が最後まで完成したかは分かりません。同じように be＋動詞の-ing形は、基準時の前後に広がる動作を途中から捉えます。Nana wrote a letter last night. は昨夜の手紙を書く出来事を一まとまりで述べ、通常は書き上げたと読みます。一方、Nana was writing a letter at nine. は9時の作業中の場面で、書き上げたかは未確定です。' },
    { type: 'example', title: '例題1：文に書かれていない終点', body: 'At nine, Nana was writing a letter. At nine ten, the lights went out. She put down her pen.\n①9時にしていたことは何か。②手紙は完成したと言えるか。③停電が起きた時刻を答えよう。', answer: '①手紙を書いていた。was writing は9時を作業の途中として示します。②この文章だけでは完成したとは言えません。put down her pen はペンを置いたという動作で、完成を意味しません。③9時10分。9時からは10分後ですが、作業の開始時刻は不明なので「全部で10分書いた」とも言えません。' },
    { type: 'note', variant: 'warn', content: '「日本語で〜している」なら必ず進行形、ではありません。I know the route.（道順を知っている）の know のように、状態を表す動詞は通常は単純形を使います。ただし動詞ごとに意味が変わることがあります。I think this route is safer. は判断、I am thinking about another route. は検討中の活動です。「状態動詞はどんな文脈でも-ingにできない」という絶対規則にもせず、その用法で何を表すかを確かめましょう。' },
    { type: 'heading', level: 3, content: '3．完了形は、基準時までの道のりを振り返る' },
    { type: 'text', content: '完了形は単なる「昔の話」ではありません。チェックポイントに立ち、そこまでの出来事や続いてきた状態を確かめる見方です。have＋過去分詞の have を現在形にすれば現在完了、過去形 had にすれば過去完了になります。I have checked the map. は今の足場から確認済みと述べ、I had checked the map before the trip began. は旅が始まった過去の足場から、それより前の確認を振り返ります。' },
    { type: 'table', headers: ['形と自作例文', '基準時', 'そこまでに何が成り立つか'], rows: [
      ['I have repaired the lamp.（ランプは修理済みだ。文脈によっては「修理したところだ」）', '今', '修理が今までに済んでいる'],
      ['I had repaired the lamp before Emi arrived.（エミが来る前にランプを修理していた）', '過去のエミの到着時', '修理はその到着より前に済んでいた'],
      ['I will have repaired the lamp by noon tomorrow.（明日の正午までにはランプを修理し終えているだろう）', '未来の明日の正午', '予測どおりなら、その時までに修理が済む'],
    ] },
    { type: 'text', content: '完了形でも、すべての状態が終了するわけではありません。I have known Emi for six years.（エミと知り合って6年になる）は、知っている状態が今まで続いているという読みです。完了・結果・経験・継続という分類は、同じ「今までを振り返る見方」が動詞や文脈と結びついて生まれる意味の整理です。名前の「完了」から、何でも終わったと判断しないようにします。' },
    { type: 'note', variant: 'warn', content: '現在完了は「今まで」の枠を持つので、通常の標準的な用法では、出来事の時点を yesterday や last year と特定して述べる文には過去形を使います。I repaired the lamp yesterday. が基本です。ただし現在完了文に過去を示す語が一切置けないのではありません。I have used this lamp since last year. の since last year は、終了した過去の枠ではなく、今まで続く期間の出発点を示しています。' },
    { type: 'heading', level: 3, content: '4．物語は、述べた順に起きるとは限らない' },
    { type: 'text', content: '映画が途中で回想に切り替わるように、物語は「次の出来事」だけでなく背景や前の出来事へ移ります。過去形は主筋を進めることが多く、過去進行形はそのときの背景を、過去完了形は過去の足場より前の事情を示すことが多い形です。ただしこれは読解の手がかりで、単純過去が必ず主筋、文の順番が必ず時間順という規則ではありません。時刻や接続詞も一緒に読みます。' },
    { type: 'example', title: '例題2：回想を挟んだ四文を並べ直す', body: 'At six, I reached the studio. Mei was painting a sign. She had mixed the blue paint at five thirty. At six ten, we carried the sign outside.\n到着・絵の具の調合・看板の運び出しを実際の順に並べよう。また、6時に続いていた動作と、開始時刻が不明な動作を答えよう。', answer: '順序は「5時30分に調合 → 6時に私が到着 → 6時10分に二人で運び出す」です。had mixed は6時の到着という過去の足場より前へ戻る回想なので、第3文の出来事が最も早いと分かります。6時にはメイが看板を塗っていました。was painting はその途中を示すため、塗り始めた正確な時刻は不明です。調合から到着までは30分、到着から運び出しまでは10分ですが、塗装に40分かかったとは結論できません。' },
    { type: 'list', ordered: true, items: [
      'まず at six などの時刻と、reached・was painting・had mixed などの動詞句に印を付ける。',
      '現在の足場を置く。例題2では reached によって6時の到着へ移る。',
      '進行形は足場を含む帯、完了形は足場までの振り返りとして、紙に出来事を並べる。開始・終了が不明なら空けておく。',
      'at six ten で新しい足場へ移る。本文から確定する順序と、自分が補った推測を分ける。',
    ] },
    { type: 'note', variant: 'warn', content: '「二つの過去があれば早い方は必ず過去完了」ではありません。After Mei mixed the paint, she painted the sign. は after が順序を明示するので、両方が過去形でも自然です。過去完了は、過去の足場から前を振り返ることを明示したいときに役立ちます。一度回想に入ったあと、十分に文脈が整えば単純過去で回想を続ける文章もあります。' },
    { type: 'heading', level: 3, content: '5．完了進行形は、そこまで続いた活動に光を当てる' },
    { type: 'text', content: '成果物の数を数えるか、汗をかいた作業の道のりを見るかで伝えたいことは変わります。have／has been＋動詞の-ing形は、今まで続いた活動や最近までの活動に焦点を当てます。I have painted three signs. は完成した3枚という成果に注目し、I have been painting signs for two hours. は2時間の作業に注目します。後者だけでは完成した枚数は分かりません。過去の基準時なら had been painting にします。' },
    { type: 'example', title: '例題3：完了進行形は必ず「今この瞬間も」か', body: 'I have been painting the door, but I have just stopped for lunch. There is paint on my hands.\n①今も休まず塗り続けているか。②手に絵の具が付いていることと最初の動詞句は、どうつながるか。', answer: '①いいえ。have just stopped for lunch が、昼食のためについ先ほど作業をやめたと明示しています。②have been painting は最近まで続けていた作業に焦点を当て、その作業が今の手の状態を説明しています。現在完了進行形は発話の瞬間も必ず動作中という意味ではありません。また、ドア全体を塗り終えたかは書かれていません。' },
    { type: 'heading', level: 3, content: '6．未来にも「足場」と「そこまで」がある' },
    { type: 'text', content: '明日の正午に作業を始めるのと、明日の正午に完成品を見せられるのは違います。will have＋過去分詞は未来の基準時までを振り返り、will be＋動詞の-ing形は未来の基準時での途中を描きます。At noon tomorrow, I will be repairing the lamp. は正午に修理中という予測で、By noon tomorrow, I will have repaired the lamp. は正午までに修理済みという予測です。by は「その時までに」の期限を示し、その時ちょうどに終わるとは限りません。どちらも未来についての見通しで、実現済みの事実ではありません。' },
    { type: 'note', variant: 'tip', content: '時を表す副詞節では未来のことにも通常は現在形を使います。When I finish the sign tomorrow, I will call you. は「明日、看板を仕上げたら電話する」で、finish は習慣ではなく未来の一回の出来事です。一方、I do not know when she will finish. の when 節は「いつ終えるか」という know の目的語になる名詞節なので、同じ規則を機械的に当てはめません。' },
    { type: 'practice', title: '練習：時間線と判断の根拠を言葉にしよう', problems: [
      { body: 'At seven, Rui was making breakfast. He had bought the bread at six thirty. ①買い物と7時の場面の前後関係、②朝食作りの開始時刻が分かるかを答えよ。', answer: '①パンを買ったのは6時30分で、7時の朝食作りの場面より30分前です。had bought が過去の足場より前を示します。②開始時刻は不明です。was making は7時に作業の途中だったことを示すだけです。' },
      { body: 'I have read this book twice. / I read this book last Sunday. 二つの文の時間の足場はどう違うか。', answer: '前者は今までの経験を振り返って2回読んだと述べる現在完了です。後者は先週の日曜日という終了した過去の枠に出来事を置く過去形です。前者だけでは2回の読書の具体的な日付は分かりません。' },
      { body: 'Mika has been practicing the piano for an hour. この一文から「今も必ず鍵盤を弾いている」「一曲を仕上げた」のどちらかを断定できるか。', answer: 'どちらも断定できません。1時間続いた練習に焦点がありますが、今も練習中の場合と、ごく最近まで練習していた場合があります。練習したという活動と、一曲を仕上げたという達成も別です。前後の情報が必要です。' },
      { body: 'By five tomorrow, I will have packed all the boxes. は、明日5時に箱詰めを開始するという意味か。基準時と作業の関係を答えよ。', answer: 'いいえ。基準時は明日5時で、その時までにはすべての箱を詰め終えているという見通しです。開始時刻は不明で、5時より前に終了する可能性もあります。' },
      { body: 'After Yui locked the door, she walked to the station. 早い出来事が過去形なのは誤りか。', answer: '誤りではありません。after が「施錠してから駅へ歩いた」という順序を示しています。過去の出来事を二つ述べるだけで、必ず早い方を had locked にしなければならないわけではありません。' },
    ] },
    { type: 'quiz', title: '確認クイズ：本文が保証することだけを選ぶ', questions: [
      { question: 'When I entered the kitchen, Saki had washed the cups. から分かる順序は？', choices: ['私が入室した時には、カップを洗い終えていた', '私の入室後に初めてカップを洗った', '私の入室と同時に洗い始めた'], answerIndex: 0, explanation: 'entered の過去の足場より前の洗浄を had washed が示します。「過去完了だから大昔」ではなく、二つの出来事の相対的な前後関係です。' },
      { question: 'At ten, Ken was drawing a circle. この文だけで確実に言えるのは？', choices: ['10時ちょうどに描き始めた', '10時に円を描く途中だった', '10時までに円を完成させた'], answerIndex: 1, explanation: '過去進行形は10時という基準時を動作の途中として示します。開始と完成の時刻は確定しません。' },
      { question: 'I have known Hana since last year. の since last year の役割は？', choices: ['昨年だけ知っていて今は知らないと限定する', '昨年の特定日に会った回数を示す', '今まで続く状態の出発点を示す'], answerIndex: 2, explanation: 'since は状態が始まった時点を示します。know は通常状態を表し、have known で今までの継続を述べられます。完了という名称でも終了を意味しません。' },
      { question: '「明日の3時までには報告書を仕上げているだろう」と、未来の基準時までの完了を明示する文は？', choices: ['I will have finished the report by three tomorrow.', 'I was finishing the report at three yesterday.', 'I will be writing the report at three tomorrow.'], answerIndex: 0, explanation: 'will have finished は未来の基準時までの完了。will be writing は未来の3時に執筆中で、完成を保証しません。' },
      { question: 'I have been running, but I stopped a minute ago. について適切な説明は？', choices: ['現在完了進行形なので stopped と矛盾する', '最近まで続いた走る活動を述べ、1分前の停止とも両立する', '昨日だけ走っていたことを表す'], answerIndex: 1, explanation: '現在完了進行形は最近までの活動と現在とのつながりも表せます。発話時に必ず活動中という規則ではありません。' },
    ] },
    { type: 'note', variant: 'tip', content: '最後の確認は三問です。「どこに足場を置く？」「そこでは途中、それともそこまでを振り返る？」「開始・終了・順序のどこまでが本文に書かれている？」。動詞の形だけで時間線を完成させようとせず、時を示す語と文脈で空欄を埋め、書かれていない時間は不明のまま残しましょう。' },
  ],
};
