import type { Lesson } from '../types.ts';

export const lesson: Lesson = {
  id: 'up-quantum-spin',
  title: 'スピン1/2と測定——基底を変えると確率はどう変わるか',
  summary: 'Stern–Gerlach型測定の概念を出発点に、二成分の状態ベクトル、ボルンの規則、相対位相、測定後の状態を計算で結び付ける。',
  objectives: [
    'スピン1/2の測定値と期待値を区別し、角運動量の単位を説明できる。',
    'z基底とx基底の間で状態を展開し、内積の絶対値の二乗から確率を求められる。',
    '同じz測定確率を与える状態でも、相対位相によりx測定確率が変わることを説明できる。',
    '理想的な射影測定の結果を条件として、次の測定の確率を計算できる。',
  ],
  blocks: [
    { type: 'heading', level: 3, content: '1．二つの結果を持つ角運動量' },
    { type: 'text', content: 'スピンは粒子に固有の角運動量です。小球が表面を回転させているという古典的な自転の模型を、そのまま当てはめることはできません。スピン1/2では、任意に選んだ一つの軸に沿う成分を理想的に測定すると、結果は二つだけです。ここでは空間の運動とは別に、スピンの二次元の状態空間だけを扱います。' },
    { type: 'formula', tex: String.raw`S_z=+\frac{\hbar}{2}\ \text{または}\ -\frac{\hbar}{2},\qquad \hbar=\frac{h}{2\pi}`, display: true },
    { type: 'text', content: String.raw`$\hbar$の単位はJ·s（kg·m²/s）であり、測定結果も角運動量の単位です。「1/2」は無次元の量子数であって、測定結果が0.5 Jという意味ではありません。またスピンの大きさの二乗は$S^2=s(s+1)\hbar^2=3\hbar^2/4$であり、一つの成分の二乗$\hbar^2/4$とは異なります。` },
    { type: 'heading', level: 3, content: '2．Stern–Gerlach型測定を概念として読む' },
    { type: 'text', content: 'Stern–Gerlach（シュテルン–ゲルラッハ）型の考え方では、不均一な磁場と磁気モーメントの相互作用によって、内部状態の違いを空間的な分岐に対応させます。理想化されたスピン1/2の測定では、選んだ軸について二つの結果を区別します。本記事ではその二つを「＋」「−」と呼び、装置の作製・調整・実験操作は扱いません。' },
    { type: 'note', variant: 'warn', content: '磁気モーメントとスピンの比例係数には符号があり、画面上の「上側」が必ず正のスピン成分とは限りません。原子では軌道角運動量や核スピンも関わるため、どんな原子でも単純な二準位模型になるわけではありません。また、空間的に分けただけのコヒーレントな状態と、結果が記録される測定とは区別します。以下の計算は、二準位として記述できる系の理想射影測定を仮定します。' },
    { type: 'heading', level: 3, content: '3．z基底：係数は確率ではなく確率振幅' },
    { type: 'formula', tex: String.raw`|+z\rangle=\begin{pmatrix}1\\0\end{pmatrix},\quad |-z\rangle=\begin{pmatrix}0\\1\end{pmatrix},\quad |\psi\rangle=\alpha|+z\rangle+\beta|-z\rangle,\quad |\alpha|^2+|\beta|^2=1`, display: true },
    { type: 'text', content: String.raw`$|+z\rangle$と$|-z\rangle$は正規直交基底です。内積は同じ基底同士なら1、異なる基底同士なら0になります。複素数$\alpha,\beta$は無次元の確率振幅であり、$P(z+)=|\alpha|^2$、$P(z-)=|\beta|^2$がボルンの規則です。ブラ$\langle\psi|$はケット$|\psi\rangle$の複素共役転置なので、複素数を含む内積では共役を忘れてはいけません。` },
    { type: 'example', title: '例題1：確率と期待値を分ける', body: String.raw`状態が$|\psi\rangle=(\sqrt{3}/2)|+z\rangle+(i/2)|-z\rangle$である。z成分の各確率と期待値を求めよ。`, answer: String.raw`絶対値の二乗から$P(z+)=3/4$、$P(z-)=1/4$。和は1です。期待値は$(3/4)(\hbar/2)+(1/4)(-\hbar/2)=\hbar/4$。これは多数回の結果の平均を予測する値であり、1回の測定で$\hbar/4$が出るという意味ではありません。` },
    { type: 'heading', level: 3, content: '4．x基底：基底変更は状態を変える操作ではない' },
    { type: 'formula', tex: String.raw`|+x\rangle=\frac{|+z\rangle+|-z\rangle}{\sqrt{2}},\qquad |-x\rangle=\frac{|+z\rangle-|-z\rangle}{\sqrt{2}}`, display: true },
    { type: 'text', content: '同じ状態でも、どの成分を測るかによって使用する固有状態の基底が異なります。上式はx成分の固有状態をz基底で書いたものです。基底を変更して座標を書き直すだけでは、物理的な状態は変化しません。一方、どの成分を実際に測るかを変えると、予測する確率分布は変わります。' },
    { type: 'derivation', title: '一般の状態をx測定へ読み替える', steps: [
      { label: '内積で振幅を取り出す', tex: String.raw`\langle+x|\psi\rangle=\frac{\alpha+\beta}{\sqrt{2}},\qquad \langle-x|\psi\rangle=\frac{\alpha-\beta}{\sqrt{2}}` },
      { label: '絶対値の二乗を取る', tex: String.raw`P(x+)=\frac{|\alpha+\beta|^2}{2},\qquad P(x-)=\frac{|\alpha-\beta|^2}{2}` },
      { label: '規格化を用いて干渉項を表示する', tex: String.raw`P(x\pm)=\frac12\pm\operatorname{Re}(\alpha^*\beta)`, note: '二つの確率の和は1。先に確率を足すのではなく、振幅を足してから二乗する。' },
    ] },
    { type: 'example', title: '例題2：同じz確率でも相対位相が違う', body: String.raw`状態Aを$(|+z\rangle+|-z\rangle)/\sqrt{2}$、状態Bを$(|+z\rangle+i|-z\rangle)/\sqrt{2}$とする。z測定とx測定の確率を比べよ。`, answer: String.raw`z測定ではどちらも＋と−が各1/2。x測定ではAの＋振幅が1、−振幅が0なので、確率は1と0です。Bの振幅は$(1+i)/2$と$(1-i)/2$で、絶対値の二乗はいずれも$(1^2+1^2)/4=1/2$。z測定の統計だけではAとBを区別できません。` },
    { type: 'note', variant: 'tip', content: String.raw`状態全体を$e^{i\chi}$倍する全体位相は、すべての測定確率を変えません。一方、二つの係数の間の相対位相は例題2のように別の基底での確率を変えます。また「＋と−が半々の古典的な混合」と、純粋状態$|+x\rangle$も別物です。z固有状態を半々に混ぜた集団ではxの＋確率は1/2ですが、$|+x\rangle$では1です。` },
    { type: 'heading', level: 3, content: '5．傾いた軸と半角の確率' },
    { type: 'text', content: String.raw`測定軸$\boldsymbol n$のz軸からの極角を$\theta$、方位角を$\phi$とすると、以下の位相規約で正の固有状態を書けます。角度はラジアンを基本とし、例題では度を明記します。$\boldsymbol n$は単位ベクトルです。` },
    { type: 'formula', tex: String.raw`|+n\rangle=\cos\frac{\theta}{2}|+z\rangle+e^{i\phi}\sin\frac{\theta}{2}|-z\rangle,\qquad P(n+\mid +z)=|\langle+n|+z\rangle|^2=\cos^2\frac{\theta}{2}`, display: true },
    { type: 'example', title: '例題3：軸の角度が60°なら', body: String.raw`初期状態$|+z\rangle$について、z軸から60°傾いた軸の成分を測る。＋と−の確率を求めよ。`, answer: '＋確率はcos²30° = 3/4、−確率は1 − 3/4 = 1/4です。角度そのものではなく半角を使います。検算として、傾き0°では＋確率1、90°では1/2、180°では0となり、同じ軸・直交軸・逆向きの軸に対応します。' },
    { type: 'heading', level: 3, content: '6．測定した後の状態を追う' },
    { type: 'text', content: String.raw`理想射影測定では、z測定で＋という結果が得られた後の条件付き状態は$|+z\rangle$です。直後に同じ軸を再測定すれば＋が確率1で得られます。ただし測定間の時間発展や外部との相互作用を無視する条件付きの主張です。「確率を知った」だけでなく、次の予測に使う状態を測定結果に応じて更新します。` },
    { type: 'example', title: '例題4：途中の測定結果を区別する', body: String.raw`初期状態$|+z\rangle$でxを測定し、その後にzを測定するという理想的な測定列を考える。時間発展は無視する。xの結果が＋だったという条件で最後のz＋確率はいくらか。また、途中のx結果を記録した後で集計時に無視した場合はどうか。`, answer: String.raw`条件付き状態は$|+x\rangle$なので最後のz＋確率は1/2。「途中がx＋かつ最後がz＋」という同時確率なら$(1/2)(1/2)=1/4$です。途中のx−でも最後のz＋は1/2なので、xの記録を集計で無視すると$(1/2)(1/2)+(1/2)(1/2)=1/2$。途中に測定がなければz＋は1であり、測定の有無は同じではありません。` },
    { type: 'note', variant: 'warn', content: '「測定結果を無視する」は「測定しない」と同じではありません。ここでは結果が記録された射影測定を仮定しているので、異なる結果の経路は確率を足します。記録を伴わないコヒーレントな分岐を再結合する問題では干渉を考える必要があり、この確率の足し算だけでは扱えません。' },
    { type: 'practice', title: '練習問題：振幅・確率・条件を言葉にする', problems: [
      { body: String.raw`$|\psi\rangle=(3|+z\rangle+4|-z\rangle)/5$のz＋確率、x＋確率を求めよ。`, answer: String.raw`z＋は$9/25$。x＋振幅は$7/(5\sqrt{2})$なので確率は$49/50$。x−は$1/50$で、和が1になることも確かめられます。` },
      { body: String.raw`$|\psi\rangle=(|+z\rangle-|-z\rangle)/\sqrt{2}$のz測定とx測定の結果を予測せよ。`, answer: String.raw`zの＋と−は各1/2。一方、この状態は$|-x\rangle$そのものなので、xでは−が確率1です。負号はz確率を変えませんが、xでの振幅の干渉を変えます。` },
      { body: String.raw`$|+z\rangle$についてz軸から120°傾いた軸の＋確率を求めよ。`, answer: 'cos²60° = 1/4です。残りの−確率は3/4。cos²120°も偶然1/4になるため、この数値だけで公式を覚えず、半角を使う根拠も確認しましょう。' },
      { body: String.raw`初期状態$|+z\rangle$でx測定の−が得られた直後に、もう一度xを測る。時間発展はない。＋確率はいくらか。`, answer: String.raw`0です。最初の結果を条件とした状態は$|-x\rangle$なので、同じ理想測定では−が確実です。初期状態のx確率1/2をそのまま再使用してはいけません。` },
    ] },
    { type: 'quiz', title: '確認クイズ', questions: [
      { question: 'スピン1/2のz成分を1回理想測定した結果として可能な値はどれか。', choices: ['0だけ', '＋ℏ/2または−ℏ/2', '＋ℏ/4または−ℏ/4', '−ℏ/2から＋ℏ/2までのすべての値'], answerIndex: 1, explanation: '測定値は演算子の固有値である二つに限られます。期待値はその中間の値を取れますが、1回の測定値とは異なります。' },
      { question: String.raw`$|+z\rangle$をx基底で表すとどうなるか。`, choices: [String.raw`$|+x\rangle$`, String.raw`$(|+x\rangle+|-x\rangle)/\sqrt{2}$`, String.raw`$(|+x\rangle-|-x\rangle)/\sqrt{2}$`, String.raw`$|+x\rangle+|-x\rangle$`], answerIndex: 1, explanation: 'x基底の定義を足すと√2倍のz＋状態になります。最後の選択肢は規格化されていません。' },
      { question: '二つの純粋状態がz測定で同じ確率を与えるとき、必ず正しいのはどれか。', choices: ['あらゆる測定で同じ確率を与える', '相対位相も必ず同じである', 'z測定の確率だけでは相対位相を決められない', 'どちらの状態も古典的な混合である'], answerIndex: 2, explanation: 'z確率は各係数の絶対値の二乗のみを表します。例題2のように相対位相が異なるとx測定で異なる確率が得られます。' },
      { question: '時間発展がない理想射影測定で、z＋という結果の直後にzを再測定した。z＋の確率はどれか。', choices: ['0', '1/4', '1/2', '1'], answerIndex: 3, explanation: '最初の結果を条件とした状態はz＋の固有状態なので、同じ測定結果が確実に得られます。' },
    ] },
    { type: 'heading', level: 3, content: '学習範囲と参考文献' },
    { type: 'text', content: '理論の参照先：J. J. Sakurai・Jim Napolitano『Modern Quantum Mechanics』第3版（Cambridge University Press, 2021）、第1章のStern–Gerlach型測定、状態ベクトル、測定の記述。本記事の例題はこれらの標準的な量子力学の規則から作成した計算問題です。実測統計や史的な実験の再現を示すものではありません。装置の有限分解能、粒子の空間運動、環境との相互作用は模型の外に置いています。' },
  ],
};
